#!/usr/bin/env python3
"""Generate complete es.js from en.js structure with Spanish translations."""

import re

# Read en.js to get the structure (comments + keys order)
with open('frontend/src/lib/i18n/en.js', 'r') as f:
    en_content = f.read()

# Spanish translations for ALL keys
ES = {
    # Common
    'app_name': 'Valuora',
    'tagline': 'Valoraci\u00f3n Empresarial Profesional',
    'loading': 'Cargando...',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'confirm': 'Confirmar',
    'back': 'Volver',
    'next': 'Siguiente',
    'close': 'Cerrar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'export': 'Exportar',
    'download': 'Descargar',
    'submit': 'Enviar',
    'edit': 'Editar',
    'view': 'Ver',
    'copy': 'Copiar',
    'share': 'Compartir',
    'yes': 'S\u00ed',
    'no': 'No',
    'or': 'o',
    'of': 'de',
    'error': 'Error',
    'success': '\u00c9xito',

    # Auth
    'login': 'Iniciar Sesi\u00f3n',
    'register': 'Registrarse',
    'logout': 'Cerrar Sesi\u00f3n',
    'email': 'Correo Electr\u00f3nico',
    'password': 'Contrase\u00f1a',
    'confirm_password': 'Confirmar Contrase\u00f1a',
    'full_name': 'Nombre Completo',
    'forgot_password': '\u00bfOlvidaste tu contrase\u00f1a?',
    'reset_password': 'Restablecer Contrase\u00f1a',
    'verify_email': 'Verificar Correo',
    'already_have_account': '\u00bfYa tienes una cuenta?',
    'dont_have_account': '\u00bfNo tienes una cuenta?',
    'create_account': 'Crear Cuenta',
    'login_success': 'Sesi\u00f3n iniciada correctamente',
    'register_success': '\u00a1Cuenta creada! Revisa tu correo para verificar.',

    # Navigation
    'nav_dashboard': 'Panel',
    'nav_new_analysis': 'Nueva Valoraci\u00f3n',
    'nav_simulator': 'Simulador',
    'nav_compare': 'Comparar',
    'nav_wacc_calculator': 'Calculadora WACC',
    'nav_inverse_projection': 'Proyecci\u00f3n Inversa',
    'nav_pitch_deck': 'Pitch Deck',
    'nav_trash': 'Papelera',
    'nav_profile': 'Perfil',
    'nav_notifications': 'Notificaciones',
    'nav_partner': 'Socio',
    'nav_admin': 'Administrador',

    # Dashboard
    'dashboard_title': 'Mis Valoraciones',
    'dashboard_empty': '\u00a1A\u00fan no tienes valoraciones. Crea tu primera!',
    'dashboard_new_analysis': 'Nueva Valoraci\u00f3n',
    'dashboard_total_analyses': 'Total de An\u00e1lisis',
    'dashboard_completed': 'Completados',

    # Analysis
    'analysis_company_name': 'Nombre de la Empresa',
    'analysis_sector': 'Sector',
    'analysis_revenue': 'Ingreso Anual',
    'analysis_net_margin': 'Margen Neto',
    'analysis_growth_rate': 'Tasa de Crecimiento',
    'analysis_debt': 'Deuda Total',
    'analysis_cash': 'Efectivo y Equivalentes',
    'analysis_founder_dependency': 'Dependencia del Fundador',
    'analysis_projection_years': 'A\u00f1os de Proyecci\u00f3n',
    'analysis_ebitda': 'EBITDA',
    'analysis_employees': 'N\u00famero de Empleados',
    'analysis_years_in_business': 'A\u00f1os en el Negocio',
    'analysis_equity_value': 'Valor del Patrimonio',
    'analysis_risk_score': 'Puntuaci\u00f3n de Riesgo',
    'analysis_maturity_index': '\u00cdndice de Madurez',
    'analysis_create': 'Crear An\u00e1lisis',
    'analysis_processing': 'Procesando tu valoraci\u00f3n...',
    'analysis_completed': 'Valoraci\u00f3n Completada',
    'analysis_failed': 'Valoraci\u00f3n Fallida',

    # Plans
    'plan_professional': 'Valoraci\u00f3n Profesional',
    'plan_professional_desc': 'M\u00e9todos DCF + Scorecard + Checklist con reporte b\u00e1sico',
    'plan_investor_ready': 'Valoraci\u00f3n Avanzada',
    'plan_investor_ready_desc': 'Los 6 m\u00e9todos + reporte completo + simulador + benchmarks',
    'plan_fundraising': 'Valoraci\u00f3n Completa',
    'plan_fundraising_desc': 'Todo incluido + an\u00e1lisis IA + hoja de ruta + soporte prioritario',
    'plan_price_professional': '$990',
    'plan_price_investor_ready': '$2.490',
    'plan_price_fundraising': '$4.990',
    'plan_one_time': 'pago \u00fanico',
    'plan_select': 'Seleccionar Plan',
    'plan_most_popular': 'M\u00e1s Popular',

    # Valuation Methods
    'method_dcf': 'Flujo de Caja Descontado (DCF)',
    'method_scorecard': 'M\u00e9todo Scorecard',
    'method_checklist': 'M\u00e9todo Checklist / Berkus',
    'method_venture_capital': 'M\u00e9todo de Capital de Riesgo',
    'method_multiples': 'M\u00faltiplos de Comparables',
    'method_all': 'Resumen de Todos los M\u00e9todos',

    # Reports
    'report_download': 'Descargar Reporte',
    'report_generating': 'Generando reporte...',
    'report_ready': 'Reporte Listo',
    'report_pages': '25+ p\u00e1ginas',

    # Payment
    'payment_title': 'Pago',
    'payment_processing': 'Procesando pago...',
    'payment_success': '\u00a1Pago confirmado!',
    'payment_failed': 'Pago fallido',
    'payment_history': 'Historial de Pagos',
    'payment_amount': 'Monto',
    'payment_status': 'Estado',
    'payment_date': 'Fecha',
    'payment_method': 'M\u00e9todo',

    # Partner
    'partner_dashboard': 'Panel de Socio',
    'partner_clients': 'Clientes',
    'partner_commissions': 'Comisiones',
    'partner_finance': 'Finanzas',
    'partner_marketing': 'Marketing',
    'partner_referral_link': 'Enlace de Referidos',

    # Footer
    'footer_privacy': 'Pol\u00edtica de Privacidad',
    'footer_terms': 'T\u00e9rminos de Uso',
    'footer_contact': 'Contacto',
    'footer_rights': '\u00a9 {year} Valuora. Todos los derechos reservados.',

    # Landing Page - Legacy
    'hero_title': 'Conoce el Valor Real de tu Empresa',
    'hero_subtitle': 'Valoraci\u00f3n empresarial profesional con 6 m\u00e9todos probados. Obt\u00e9n tu reporte ejecutivo en minutos.',
    'hero_cta': 'Iniciar Valoraci\u00f3n',
    'hero_secondary_cta': 'Diagn\u00f3stico Gratuito',
    'hero_trusted_by': 'M\u00e1s de {count}+ empresas conf\u00edan en nosotros',

    'features_title': '\u00bfPor qu\u00e9 elegir Valuora?',
    'feature_dcf': 'Valoraci\u00f3n DCF',
    'feature_dcf_desc': 'An\u00e1lisis de Flujo de Caja Descontado con datos de Damodaran y tasas de mercado reales.',
    'feature_multi_method': '6 M\u00e9todos de Valoraci\u00f3n',
    'feature_multi_method_desc': 'DCF, Scorecard, Checklist, M\u00e9todo VC, M\u00faltiplos y An\u00e1lisis IA.',
    'feature_report': 'Reporte Ejecutivo',
    'feature_report_desc': 'Reporte profesional de 25+ p\u00e1ginas con gr\u00e1ficos, an\u00e1lisis y recomendaciones.',
    'feature_fast': 'Resultados en Minutos',
    'feature_fast_desc': 'Lo que a los consultores les toma semanas, Valuora lo entrega en minutos.',

    'pricing_title': 'Precios Simples y Transparentes',
    'pricing_subtitle': 'Pago \u00fanico. Sin suscripciones.',

    'faq_title': 'Preguntas Frecuentes',

    # Errors
    'error_network': 'Error de red. Verifica tu conexi\u00f3n.',
    'error_unauthorized': 'Sesi\u00f3n expirada. Por favor inicia sesi\u00f3n de nuevo.',
    'error_not_found': 'P\u00e1gina no encontrada.',
    'error_server': 'Error del servidor. Intenta de nuevo m\u00e1s tarde.',
    'error_validation': 'Por favor revisa los campos del formulario.',

    # Pages Common
    'financial_data': 'Datos Financieros',
    'restore': 'Restaurar',
    'resend': 'Reenviar',
    'deactivate': 'Desactivar',
    'activate': 'Activar',
    'copied': '\u00a1Copiado!',
    'mark_paid': 'Marcar Pagado',
    'paid': 'Pagado',
    'optional': '(opcional)',
    'verified': 'Verificados',
    'unverified': 'No verificados',
    'administration': 'Administraci\u00f3n',
    'partner_mode': 'Modo Socio',
    'view_result': 'Ver Resultado',
    'solution_found': 'Soluci\u00f3n encontrada',
    'minimum_pct': 'M\u00ednimo (%)',
    'maximum_pct': 'M\u00e1ximo (%)',
    'simulated': 'simulado',
    'net_income': 'ingreso neto',
    'consulting_firm': 'Consultor\u00eda / Firma',

    # Validation
    'name_cannot_be_empty': 'El nombre no puede estar vac\u00edo.',
    'action_cannot_be_undone': 'Esta acci\u00f3n no se puede deshacer.',
    'analysis_not_found': 'An\u00e1lisis no encontrado.',
    'page_not_found': 'P\u00e1gina no encontrada',
    'page_not_found_desc': 'La p\u00e1gina que buscas no existe o fue movida.',
    'go_home': 'Ir al Inicio',

    # Admin
    'max_uses_hint': 'M\u00e1x. usos (vac\u00edo = ilimitado)',
    'expiration_hint': 'Expiraci\u00f3n (vac\u00edo = sin expiraci\u00f3n)',

    # Partner Extra
    'utm_link_copied': '\u00a1Enlace UTM copiado!',
    'no_notes_hint': 'Sin notas. Haz clic en editar para agregar.',

    # Trash
    'trash_title': 'Papelera',
    'items_in_trash': '{count} {items} en papelera',
    'item_singular': 'elemento',
    'item_plural': 'elementos',

    # Simulator
    'simulator_title': 'Simulador \u2014 {name}',
    'equity_value_simulated': 'Valor del Patrimonio (simulado)',

    # Analysis Page
    'position_vs_sector': 'Posici\u00f3n vs Rango Sectorial (P25 \u2013 P75)',

    # Onboarding
    'onboarding_nav_hint': 'Esc para cerrar \u00b7 \u2190 \u2192 para navegar',

    # Partner Marketing
    'sales_greeting_1': '\u00bfC\u00f3mo est\u00e1s?',
    'sales_intro': 'Mi nombre es [Tu Nombre], soy de [Tu Firma].',
    'sales_greeting_2': 'Solo pasaba a saludar',
    'sales_greeting_3': '\u00bfC\u00f3mo est\u00e1s?',
    'sales_placeholder_name': '[Nombre]',
    'sales_placeholder_your_name': '[Tu Nombre]',
    'sales_and': 'y',

    # Extra UI
    'go_dashboard': 'Ir al Panel',
    'home_page': 'P\u00e1gina de Inicio',
    'reanalyze': 'Re-analizar',
    'reanalyzing': 'Re-analizando\u2026',
    'profile_updated': 'Perfil actualizado',
    'all_filter': 'Todos',
    'active_filter': 'Activos',
    'inactive_filter': 'Inactivos',
    'active_status': 'Activo',
    'inactive_status': 'Inactivo',
    'leave_blank_to_clear': 'Dejar en blanco para borrar',
    'code_label': 'C\u00f3digo',
    'description_label': 'Descripci\u00f3n',
    'internal_use': 'Uso interno',
    'day_singular': 'd\u00eda',
    'day_plural': 'd\u00edas',
    'dismiss': 'Descartar',
    'next_goal': 'Pr\u00f3xima meta',
    'all_goals_reached': '\u00a1Todas las metas alcanzadas!',
    'goals': 'metas',
    'source_label': 'Fuente',
    'medium_label': 'Medio',
    'campaign_label': 'Campa\u00f1a',
    'refund': 'Reembolsar',
    'new_clients_singular': '\u00a1nuevo cliente!',
    'new_clients_plural': '\u00a1nuevos clientes!',
    'actions': 'Acciones',
    'verified_badge': 'verificado',
    'verify_email_action': 'Verificar email',
    'adjust_params': 'Ajusta par\u00e1metros y recalcula en tiempo real',
    'calculating': 'Calculando...',
    'calculate': 'Calcular',
    'notifications': 'Notificaciones',
    'mark_all_read': 'Marcar todo como le\u00eddo',
    'mark_as_read': 'Marcar como le\u00eddo',
    'no_notifications': 'Sin notificaciones',
    'min_label': 'M\u00ednimo',
    'max_label': 'M\u00e1ximo',
    'see_result': 'Ver Resultado',
    'position_vs_range': 'Posici\u00f3n vs Rango Sectorial',
    'sign_in': 'Iniciar sesi\u00f3n',

    # Notifications Page
    'track_recent_events': 'Rastrea tus eventos recientes',
    'filter_all': 'Todos',
    'filter_analyses': 'An\u00e1lisis',
    'filter_payments': 'Pagos',
    'filter_pitchdeck': 'Pitch Deck',
    'nothing_here_yet': 'Nada aqu\u00ed todav\u00eda.',
    'previous': 'Anterior',

    # Sidebar
    'nav_overview': 'Resumen',
    'nav_clients': 'Clientes',
    'nav_commissions': 'Comisiones',
    'nav_finance': 'Finanzas',
    'nav_marketing': 'Marketing',
    'sidebar_processing': 'procesando',
    'sidebar_partner_section': 'Socio',
    'sidebar_portfolio': 'Portafolio',
    'sidebar_completed': 'Completados',
    'sidebar_highest': 'Mayor',
    'sidebar_log_out': 'Cerrar Sesi\u00f3n',
    'sidebar_user_fallback': 'Usuario',

    # Landing Navbar
    'nav_how_it_works': 'C\u00f3mo funciona',
    'nav_features': 'Caracter\u00edsticas',
    'nav_plans': 'Planes',
    'nav_methodology': 'Metodolog\u00eda',
    'nav_partners': 'Socios',
    'nav_sign_in': 'Iniciar sesi\u00f3n',
    'nav_start_valuation': 'INICIAR VALORACI\u00d3N',
    'nav_login_partner': 'Login Socio',

    # Sticky Bar
    'sticky_valuation_from': 'Valoraci\u00f3n desde $990',
    'sticky_pitch_deck_price': 'Pitch Deck $897',
    'sticky_one_time': 'Pago \u00fanico',
    'sticky_start': 'Iniciar \u2192',

    # Hero
    'hero_valuation_dcf': 'Valoraci\u00f3n DCF',
    'hero_pitch_deck': 'Pitch Deck',
    'hero_new_badge': 'NUEVO',
    'hero_how_much_is': '\u00bfCu\u00e1nto vale',
    'hero_your_company_worth': 'tu empresa?',
    'hero_val_subtitle': 'Valoraci\u00f3n profesional en minutos \u2014 no semanas. El rigor del DCF con interpretaci\u00f3n de IA, benchmarks sectoriales calibrados y el mismo est\u00e1ndar M&A a una fracci\u00f3n del costo.',
    'hero_val_badge_dcf': 'Motor DCF Institucional',
    'hero_val_badge_ai': 'An\u00e1lisis con Inteligencia Artificial',
    'hero_val_badge_report': 'Reporte de hasta 25 p\u00e1ginas',
    'hero_val_cta_start': 'Iniciar valoraci\u00f3n',
    'hero_val_cta_diagnostic': 'Diagn\u00f3stico Gratuito',
    'hero_val_subtext': 'Sin suscripci\u00f3n \u00b7 Resultados en minutos \u00b7 Desde $990',
    'hero_val_report_samples': 'Muestras de reportes',
    'hero_val_sample_professional': 'Valoraci\u00f3n Profesional',
    'hero_val_sample_advanced': 'Valoraci\u00f3n Avanzada',
    'hero_val_sample_complete': 'Valoraci\u00f3n Completa \u2605',
    'hero_pitch_subtitle': 'Pitch deck profesional para inversores \u2014 en minutos. Dise\u00f1o apaisado A4 con narrativa IA, panel KPI, gr\u00e1ficos de escenarios, TAM/SAM/SOM visual y matriz competitiva.',
    'hero_pitch_badge_ai': 'Narrativa IA',
    'hero_pitch_badge_waterfall': 'Waterfall + 3 Escenarios',
    'hero_pitch_badge_tam': 'TAM/SAM/SOM Visual',
    'hero_pitch_badge_design': 'A4 Apaisado \u2014 Dise\u00f1o Premium',
    'hero_pitch_cta_create': 'Crear mi pitch deck',
    'hero_pitch_cta_see_dcf': 'Ver Valoraci\u00f3n DCF',
    'hero_pitch_subtext': 'Sin suscripci\u00f3n \u00b7 Resultados en minutos \u00b7 $897 pago \u00fanico',
    'hero_pitch_sample_title': 'Muestra de pitch deck',
    'hero_pitch_view_pdf': 'Ver PDF completo \u2197',

    # Trust Badges
    'trust_data_protection': 'Protecci\u00f3n de Datos',
    'trust_ssl': 'SSL 256-bit',
    'trust_dcf': 'Metodolog\u00eda DCF',
    'trust_benchmarks': 'Benchmarks Sectoriales',

    # Mock Preview
    'mock_pitch_label': 'Pitch Deck \u00b7 Empresa X',
    'mock_pitch_round': 'Ronda Serie A \u2014 $5M',
    'mock_pitch_slides': '12 diapositivas',
    'mock_market_size': 'Tama\u00f1o de Mercado',
    'mock_tam_total': 'Total',
    'mock_sam_addressable': 'Accesible',
    'mock_som_obtainable': 'Alcanzable',
    'mock_val_equity_label': 'Valor Patrimonial Estimado',
    'mock_val_range': 'Rango: $3.1M \u2014 $5.6M',
    'mock_val_risk_score': 'Puntuaci\u00f3n de Riesgo',
    'mock_val_maturity': 'Madurez',
    'mock_val_percentile': 'Percentil',
    'mock_val_fcfe_proj': 'Proyecci\u00f3n FCFE \u2014 5 a\u00f1os',
    'badge_ai_narrative': 'Narrativa IA',
    'badge_tam_sam_som': 'TAM/SAM/SOM',
    'badge_kpi_panel': 'Panel KPI',
    'badge_dcf_gordon': 'DCF Gordon',
    'badge_sector_benchmark': 'Benchmark Sectorial',
    'badge_5yr_projection': 'Proyecci\u00f3n 5 a\u00f1os',
    'badge_ai_analysis': 'An\u00e1lisis IA',
    'mock_open': 'Abrir \u2197',

    # Engine Strip
    'strip_engine_active': 'Motor DCF v7 \u2014 Activo',
    'strip_updated_on': 'Actualizado el',
    'strip_treasury': 'Treasury 10Y:',
    'strip_beta_damodaran': 'Beta Damodaran',
    'strip_sectors': 'sectores industriales calibrados',

    # Credibility
    'cred_title': 'Metodolog\u00eda reconocida por el mercado',
    'cred_ssl': 'Encriptaci\u00f3n SSL 256-bit',
    'cred_certified_dcf': 'DCF Certificado',
    'cred_benchmarks': 'Benchmarks Sectoriales',
    'cred_damodaran': 'Beta Damodaran / NYU Stern',

    # Comparison Table
    'compare_label': 'Comparaci\u00f3n',
    'compare_title_why': '\u00bfPor qu\u00e9',
    'compare_title_different': 'es diferente?',
    'compare_traditional': 'Consultor\u00eda Tradicional',
    'compare_time': 'Tiempo',
    'compare_time_qv': 'Resultados en 5 minutos',
    'compare_time_cons': 'Semanas a meses',
    'compare_cost': 'Costo',
    'compare_cost_qv': 'Desde $990',
    'compare_cost_cons': 'De $5.000 a $50.000+',
    'compare_complexity': 'Complejidad',
    'compare_complexity_qv': 'Rellena y recibe \u2014 simple',
    'compare_complexity_cons': 'Reuniones, entrevistas, hojas de c\u00e1lculo',
    'compare_report': 'Reporte PDF',
    'compare_report_qv': 'Hasta 25 p\u00e1ginas incluidas',
    'compare_report_cons': 'Se cobra aparte o no se incluye',
    'compare_available': 'Disponible',
    'compare_available_qv': '24/7, en cualquier lugar',
    'compare_available_cons': 'Horario comercial, presencial',
    'compare_cta': 'Empezar ahora \u2014 gratis',

    # Problem / Solution
    'problem_label': 'El problema',
    'problem_title': 'Sin una valoraci\u00f3n estructurada, cualquier negociaci\u00f3n comienza con',
    'problem_asymmetry': 'asimetr\u00eda de informaci\u00f3n',
    'problem_case_stake': 'Venta de participaci\u00f3n',
    'problem_case_partner': 'Entrada de socio',
    'problem_case_fundraising': 'Captaci\u00f3n de inversi\u00f3n',
    'problem_case_exit': 'Planificaci\u00f3n de salida',
    'problem_desc': 'Las consultoras tradicionales tardan semanas y cobran entre $5.000 y $50.000. Valuora entrega un an\u00e1lisis t\u00e9cnico, fundamentado y documentado en minutos.',
    'solution_label': 'La soluci\u00f3n',
    'solution_engine_title': 'Motor Institucional',
    'solution_engine_desc': 'DCF con FCFE proyectado a 10 a\u00f1os, WACC, beta sectorial Damodaran y tasa libre de riesgo del Tesoro de EE.UU. \u2014 la misma metodolog\u00eda utilizada por consultoras de M&A.',
    'solution_engine_tag': 'Motor DCF v7',
    'solution_bench_title': 'Benchmarks Sectoriales',
    'solution_bench_desc': 'Base de datos propietaria con m\u00e1s de 50 segmentos industriales, calibrada con metodolog\u00eda Damodaran y datos de mercado. Tu valoraci\u00f3n refleja el escenario real de tu sector.',
    'solution_bench_tag': 'Base de Datos Sectorial',
    'solution_report_title': 'Reporte Defendible',
    'solution_report_desc': 'Hasta 25 p\u00e1ginas con metodolog\u00eda de c\u00e1lculo, supuestos, escenarios y an\u00e1lisis IA \u2014 listo para inversores, socios o bancos.',
    'solution_report_tag': 'PDF Premium',

    # Use Cases
    'use_cases_label': 'Casos de uso',
    'use_cases_title_prefix': 'Dise\u00f1ado para quienes necesitan',
    'use_cases_title_highlight': 'respuestas concretas',
    'use_case_sell_title': 'Due\u00f1o de negocio que quiere vender',
    'use_case_sell_desc': 'Sabe exactamente cu\u00e1nto pedir antes de iniciar cualquier negociaci\u00f3n de venta.',
    'use_case_raise_title': 'Startup captando fondos',
    'use_case_raise_desc': 'Presenta una valoraci\u00f3n profesional y defendible a inversores y fondos.',
    'use_case_accounting_title': 'Contabilidad / Consultor\u00eda',
    'use_case_accounting_desc': 'Ofrece valoraci\u00f3n como servicio adicional a tus clientes. Convi\u00e9rtete en socio.',
    'use_case_buy_title': 'Buscando comprar',
    'use_case_buy_desc': 'Eval\u00faa la empresa objetivo antes de hacer una oferta y negocia con datos reales.',

    # How It Works
    'hiw_label': 'C\u00f3mo funciona',
    'hiw_title': '4 pasos para tu valoraci\u00f3n',
    'hiw_step1_title': 'Crea tu cuenta',
    'hiw_step1_desc': 'Registro con confirmaci\u00f3n por email. Entorno seguro.',
    'hiw_step2_title': 'Env\u00eda tus datos financieros',
    'hiw_step2_desc': 'Ingreso manual o carga de estado de resultados en PDF/Excel. La IA extrae y estructura autom\u00e1ticamente.',
    'hiw_step3_title': 'Ve la vista previa',
    'hiw_step3_desc': 'Recibe indicadores clave antes de desbloquear el reporte.',
    'hiw_step4_title': 'Desbloquea el reporte completo',
    'hiw_step4_desc': 'Elige el plan y recibe el PDF ejecutivo por email.',

    # Before / After
    'transform_label': 'Transformaci\u00f3n',
    'transform_title_prefix': 'De la forma antigua a la',
    'transform_title_highlight': 'forma correcta',
    'transform_subtitle': 'La misma calidad de las mejores consultoras \u2014 sin las semanas de espera y sin el costo prohibitivo.',
    'before_tag': 'ANTES \u2014 Consultor\u00eda Tradicional',
    'before_timeframe': 'Plazo',
    'before_timeframe_val': '3 a 8 semanas',
    'before_cost_val': 'De $5.000 a $50.000',
    'before_process': 'Proceso',
    'before_process_val': 'Reuniones, entrevistas, aprobaciones',
    'before_delivery': 'Entrega',
    'before_delivery_val': 'PDF gen\u00e9rico, sin an\u00e1lisis contextual',
    'before_availability': 'Disponibilidad',
    'before_availability_val': 'Horario comercial, presencial',
    'after_tag': 'AHORA \u2014 Valuora',
    'after_timeframe_val': 'Resultados en 5 minutos',
    'after_cost_val': 'Desde $990, pago \u00fanico',
    'after_process_val': 'Rellena el formulario. Listo.',
    'after_delivery_val': 'Hasta 25 p\u00e1ginas con an\u00e1lisis estrat\u00e9gico IA',
    'after_availability_val': '24/7, cualquier dispositivo',

    # Products
    'products_label': 'Nuestros productos',
    'products_title': 'Dos herramientas para valorar y presentar tu empresa',
    'products_subtitle': 'Valoraci\u00f3n profesional y pitch deck para inversores \u2014 todo en una sola plataforma.',
    'products_val_core': 'CORE',
    'products_val_title': 'Valoraci\u00f3n DCF',
    'products_val_sub': 'Motor institucional + IA',
    'products_val_desc': 'Reporte profesional de hasta 25 p\u00e1ginas con DCF, benchmark sectorial calibrado, an\u00e1lisis de riesgo, simulador estrat\u00e9gico y narrativa IA.',
    'products_val_feat_dcf': 'DCF Gordon + Exit Multiple',
    'products_val_feat_bench': 'Benchmark Sectorial',
    'products_val_feat_ai': 'An\u00e1lisis IA',
    'products_val_feat_pages': 'Hasta 25 p\u00e1ginas',
    'products_val_cta_start': 'Iniciar',
    'products_pitch_new': 'NUEVO',
    'products_pitch_title': 'Pitch Deck',
    'products_pitch_sub': 'PDF listo para inversores',
    'products_pitch_desc': 'A4 apaisado premium con TAM/SAM/SOM visual, matriz competitiva 2\u00d72, waterfall de ingresos, panel KPI, 3 escenarios financieros, equipo con fotos y narrativa IA.',
    'products_pitch_feat_a4': 'A4 Apaisado',
    'products_pitch_feat_tam': 'TAM/SAM/SOM Visual',
    'products_pitch_feat_matrix': 'Matriz 2\u00d72',
    'products_pitch_feat_waterfall': 'Waterfall + Escenarios',
    'products_pitch_feat_kpi': 'Panel KPI',
    'products_pitch_feat_ai': 'Narrativa IA',
    'products_pitch_one_time': '/ pago \u00fanico',
    'products_pitch_cta': 'Crear',
    'products_pitch_view_sample': 'Ver muestra de pitch deck',

    # Features Section
    'features_label': 'Caracter\u00edsticas',
    'features_title_full': 'Todo para evaluar y defender el valor de tu empresa',
    'feat_dcf_title': 'Valoraci\u00f3n DCF Completa',
    'feat_dcf_desc': 'Valor estimado con DCF Gordon + Exit Multiple, DLOM y an\u00e1lisis de supervivencia.',
    'feat_pdf_title': 'Reporte PDF Premium',
    'feat_pdf_desc': 'Documento institucional con gr\u00e1ficos, proyecciones, benchmark y an\u00e1lisis estrat\u00e9gico IA.',
    'feat_sim_title': 'Simulador Interactivo',
    'feat_sim_desc': 'Cambia crecimiento, margen y tasa de descuento. La valoraci\u00f3n se recalcula al instante.',
    'feat_ai_title': 'An\u00e1lisis Estrat\u00e9gico IA',
    'feat_ai_desc': 'An\u00e1lisis narrativo con recomendaciones estrat\u00e9gicas generadas por inteligencia artificial.',
    'feat_compare_title': 'Comparar An\u00e1lisis',
    'feat_compare_desc': 'Compara hasta 4 empresas lado a lado \u2014 valoraci\u00f3n, riesgo, ingresos y m\u00faltiplos en un solo panel.',
    'feat_bench_title': 'Benchmark Estrat\u00e9gico',
    'feat_bench_desc': 'Descubre si tu margen, crecimiento y eficiencia est\u00e1n por encima o debajo del mercado.',
    'feat_cta_start_free': 'Empezar gratis',

    # Methodology
    'method_label': 'Metodolog\u00eda',
    'method_title_full': '6 capas de an\u00e1lisis para una valoraci\u00f3n defendible',
    'method_subtitle': 'Combinamos tres m\u00e9todos de valoraci\u00f3n con tres capas de ajuste \u2014 el mismo enfoque utilizado por consultoras de M&A.',
    'method_gordon_title': 'DCF \u2014 Crecimiento Gordon',
    'method_gordon_badge': 'Peso por madurez',
    'method_gordon_desc': 'Proyecta FCFE (flujo al patrimonio) a 10 a\u00f1os y calcula el Valor Terminal usando la f\u00f3rmula de Gordon. Usa Ke (Valuora) como tasa de descuento, con beta sectorial Damodaran y tasa libre de riesgo del Tesoro de EE.UU.',
    'method_gordon_tags': 'FCFE Proyectado \u00b7 Valor Terminal \u00b7 Ke \u00b7 Beta Valuora',
    'method_exit_title': 'DCF \u2014 Exit Multiple',
    'method_exit_desc': 'Mismo flujo de caja proyectado, pero el Valor Terminal se calcula aplicando un m\u00faltiplo EV/EBITDA sectorial al EBITDA del \u00faltimo a\u00f1o proyectado. Reduce la dependencia de supuestos de crecimiento perpetuo.',
    'method_exit_tags': 'EV/EBITDA \u00b7 Valor Terminal \u00b7 Exit multiple \u00b7 EBITDA Proyectado',
    'method_multiples_title': 'M\u00faltiplos Sectoriales',
    'method_multiples_badge': 'Informativo',
    'method_multiples_desc': 'Valoraci\u00f3n informativa por EV/Revenue y EV/EBITDA sectorial, con datos reales de Damodaran/NYU Stern. En v4, los m\u00faltiplos no componen el valor final.',
    'method_dlom_title': 'DLOM',
    'method_dlom_badge': '10\u201335%',
    'method_dlom_desc': 'Descuento del 10% al 35% para empresas privadas (sin liquidez de mercado). Ajustado por tama\u00f1o, madurez y liquidez del sector.',
    'method_dlom_tags': 'Descuento por Falta de Comerciabilidad \u00b7 Privadas',
    'method_survival_title': 'Tasa de Supervivencia',
    'method_survival_badge': 'BLS',
    'method_survival_desc': 'Descuento basado en la probabilidad real de supervivencia de la empresa en el horizonte de proyecci\u00f3n, con datos BLS/SBA y bonificaci\u00f3n por a\u00f1os de operaci\u00f3n.',
    'method_survival_tags': 'Probabilidad real \u00b7 Horizonte de proyecci\u00f3n',
    'method_qual_title': 'Puntuaci\u00f3n Cualitativa',
    'method_qual_badge': '\u00b115%',
    'method_qual_desc': 'Evaluaci\u00f3n de equipo, mercado, producto, tracci\u00f3n y operaciones. Ajusta \u00b115% del valor final seg\u00fan factores de riesgo no financieros.',
    'method_qual_tags': '10 preguntas \u00b7 5 dimensiones \u00b7 Factores no financieros',
    'method_ai_title': 'QV Intelligence',
    'method_ai_badge': 'IA Propietaria',
    'method_ai_desc': 'Despu\u00e9s de que el motor DCF calcula todos los n\u00fameros, QV Intelligence interpreta los resultados. Contextualiza la valoraci\u00f3n en tu sector, se\u00f1ala inconsistencias, compara con benchmarks de mercado y redacta el Resumen Ejecutivo.',
    'method_ai_tags': 'QV Intelligence \u00b7 Resumen Ejecutivo \u00b7 Contexto sectorial \u00b7 An\u00e1lisis de riesgo',
    'pipeline_result': 'Resultado: una valoraci\u00f3n t\u00e9cnica, consistente y defendible.',

    # Plans / Pricing
    'plans_label': 'Precios',
    'plans_title_full': 'Pago \u00fanico. Sin suscripci\u00f3n.',
    'plans_stripe': 'Pago seguro v\u00eda Stripe',
    'plan_pro_name': 'Valoraci\u00f3n Profesional',
    'plan_pro_desc': 'Valoraci\u00f3n DCF Completa',
    'plan_pro_pages': '~8 p\u00e1ginas',
    'plan_pro_f1': 'Valoraci\u00f3n DCF Crecimiento Gordon',
    'plan_pro_f2': 'Puntuaci\u00f3n de riesgo y madurez',
    'plan_pro_f3': 'Escenarios conservador / base / optimista',
    'plan_pro_f4': 'Reporte ejecutivo b\u00e1sico',
    'plan_pro_f5': 'Entrega por email',
    'plan_adv_name': 'Valoraci\u00f3n Avanzada',
    'plan_adv_desc': 'An\u00e1lisis completo con benchmark',
    'plan_adv_pages': '~15 p\u00e1ginas',
    'plan_adv_f1': 'Todo en Valoraci\u00f3n Profesional',
    'plan_adv_f2': 'DCF Exit Multiple + M\u00faltiplos',
    'plan_adv_f3': 'Benchmark sectorial oficial',
    'plan_adv_f4': 'DLOM + Supervivencia + P&L',
    'plan_adv_f5': 'Proyecci\u00f3n de Ingresos y FCFE',
    'plan_adv_f6': 'Tabla de sensibilidad',
    'plan_adv_f7': 'Prima de control / descuento minoritario',
    'plan_comp_name': 'Valoraci\u00f3n Completa',
    'plan_comp_desc': 'M\u00e1ximo nivel de an\u00e1lisis',
    'plan_comp_pages': '~25 p\u00e1ginas',
    'plan_comp_f1': 'Todo en Valoraci\u00f3n Avanzada',
    'plan_comp_f2': 'Gr\u00e1fico Tornado \u2014 drivers de valor',
    'plan_comp_f3': 'Monte Carlo (2.000 simulaciones)',
    'plan_comp_f4': 'Evaluaci\u00f3n cualitativa + radar de dimensiones',
    'plan_comp_f5': 'An\u00e1lisis de Estrategia de Salida',
    'plan_comp_f6': 'Matriz de Riesgo M&A',
    'plan_comp_f7': 'Plan de Mejora de Valor (IA)',
    'plan_comp_f8': 'Carta de Opini\u00f3n de Valor',
    'plan_comp_f9': 'Simulaci\u00f3n de ronda de inversi\u00f3n',
    'plan_comp_f10': 'An\u00e1lisis estrat\u00e9gico completo por IA',
    'plan_recommended': 'Recomendado',
    'plan_installment_prefix': 'o',
    'plan_installment_suffix': 'en tarjeta de cr\u00e9dito*',
    'plan_pdf_report_with': 'Reporte PDF con',
    'plan_cta': 'INICIAR VALORACI\u00d3N',
    'plan_view_sample': 'Ver muestra de reporte \u2197',
    'plan_guarantee': 'Satisfacci\u00f3n garantizada \u00b7 Pago seguro \u00b7 Soporte por email',
    'plan_installment_note': '* Planes de cuotas sujetos a intereses y comisiones del emisor de la tarjeta.',
    'pay_secure_ssl': 'SSL Seguro',
    'pay_privacy': 'Cumple con Privacidad',
    'pay_stripe': 'Powered by Stripe',
    'pay_one_time': 'Pago \u00danico',
    'pay_no_sub': 'Sin Suscripci\u00f3n',

    # Partners
    'partners_label': 'Socios',
    'partners_title': 'Convierte referidos en ingresos',
    'partners_subtitle': 'Ideal para despachos contables, consultoras y firmas de asesor\u00eda que desean ofrecer valoraci\u00f3n profesional y pitch deck para inversores como servicio adicional \u2014 y ganar el 50% de cada venta.',
    'partners_comm_title': '50% \u2014 Valoraci\u00f3n y Pitch Deck',
    'partners_comm_desc': 'Comisi\u00f3n en ambos productos. Cada venta \u2014 valoraci\u00f3n o pitch deck \u2014 ganas la mitad. Sin tope de ganancias.',
    'partners_mgmt_title': 'Gesti\u00f3n completa',
    'partners_mgmt_desc': 'Panel exclusivo para rastrear clientes, estado y comisiones en tiempo real.',
    'partners_portfolio_title': 'Tu portafolio crece',
    'partners_portfolio_desc': 'Ofrece valoraci\u00f3n y pitch deck para inversores sin invertir en equipo o tecnolog\u00eda.',
    'partners_link_title': 'Enlace de referidos',
    'partners_link_desc': 'Comparte tu enlace. Cada registro se rastrea autom\u00e1ticamente.',
    'partners_hiw_title': 'C\u00f3mo funciona',
    'partners_hiw_step1_title': 'Reg\u00edstrate como socio',
    'partners_hiw_step1_desc': 'Crea tu cuenta y activa el Modo Socio en segundos. Recibes un enlace de referidos exclusivo.',
    'partners_hiw_step2_title': 'Refiere a tus clientes',
    'partners_hiw_step2_desc': 'Comparte tu enlace o registra clientes directamente en el panel. Cada valoraci\u00f3n o pitch deck se rastrea autom\u00e1ticamente.',
    'partners_hiw_step3_title': 'Recibe tus comisiones',
    'partners_hiw_step3_desc': 'Por cada pago confirmado \u2014 ya sea valoraci\u00f3n o pitch deck \u2014 el 50% se acredita autom\u00e1ticamente a tu cuenta.',
    'partners_cta_badge': '50% COMISI\u00d3N',
    'partners_cta_title': 'Dividimos 50/50',
    'partners_cta_subtitle': 'Cada venta que refieras, la mitad es tuya.',
    'partners_cta_desc': 'Valoraci\u00f3n profesional ($990+) o Pitch Deck para inversores ($897). T\u00fa refieres, el cliente paga y el dinero va a tu cuenta. Sin tope de ganancias.',
    'partners_cta_button': 'Quiero ser socio y ganar 50%',
    'partners_cta_checks': '\u2713 Registro en 30 segundos \u00b7 \u2713 Enlace exclusivo \u00b7 \u2713 Panel con anal\u00edticas completas',

    # Objections
    'obj_label': 'Directo al grano',
    'obj_title': '\u00bfQu\u00e9 te impide empezar ahora?',
    'obj_q1': '\u00bfMi empresa es demasiado peque\u00f1a?',
    'obj_a1': 'Ninguna empresa es demasiado peque\u00f1a para una valoraci\u00f3n. El motor se calibra por tu sector y madurez \u2014 desde aut\u00f3nomos hasta empresas con $50M en ingresos.',
    'obj_q2': '\u00bfNecesito un contador para usarlo?',
    'obj_a2': 'Para nada. El formulario es guiado. Si conoces tu ingreso anual y margen aproximado, puedes terminar en menos de 5 minutos.',
    'obj_q3': 'Nunca he hecho una valoraci\u00f3n. \u00bfEs para m\u00ed?',
    'obj_a3': 'Exactamente para ti. El reporte fue dise\u00f1ado para cualquier due\u00f1o de negocio \u2014 cada indicador se explica en lenguaje claro, sin jerga.',
    'obj_q4': '\u00bfLos inversores aceptar\u00e1n este reporte?',
    'obj_a4': 'S\u00ed. Sigue la metodolog\u00eda est\u00e1ndar DCF de M&A \u2014 metodolog\u00eda de c\u00e1lculo completa, benchmark sectorial y an\u00e1lisis de sensibilidad incluidos.',

    # FAQ
    'faq_label': 'Preguntas frecuentes',
    'faq_subtitle': 'Todo lo que necesitas saber antes de empezar',
    'faq_q1': '\u00bfMi valoraci\u00f3n es confidencial?',
    'faq_a1': 'S\u00ed. Tus datos financieros est\u00e1n encriptados de extremo a extremo y nunca se comparten con terceros.',
    'faq_q2': '\u00bfSe puede usar para captar inversi\u00f3n?',
    'faq_a2': 'S\u00ed. El reporte usa la misma metodolog\u00eda DCF que las consultoras de M&A, con metodolog\u00eda de c\u00e1lculo, supuestos y benchmark sectorial \u2014 listo para presentar a inversores y fondos.',
    'faq_q3': '\u00bfCu\u00e1nto tarda en llegar el resultado?',
    'faq_a3': 'La valoraci\u00f3n se genera en minutos. Despu\u00e9s del pago, el reporte PDF completo se env\u00eda a tu email autom\u00e1ticamente.',
    'faq_q4': '\u00bfPuedo usarlo para negociar la venta de mi empresa?',
    'faq_a4': 'Absolutamente. El reporte incluye rango de valor, escenarios pesimista/optimista y benchmark sectorial \u2014 documentaci\u00f3n que fortalece tu posici\u00f3n en cualquier negociaci\u00f3n.',
    'faq_q5': '\u00bfEl pago es recurrente?',
    'faq_a5': 'No. Es un pago \u00fanico por an\u00e1lisis. Sin suscripci\u00f3n, sin pagos recurrentes.',
    'faq_q6': '\u00bfDe d\u00f3nde vienen los datos sectoriales?',
    'faq_a6': 'Base de datos sectorial propietaria con m\u00e1s de 50 segmentos industriales, calibrada con metodolog\u00eda Damodaran y datos de mercado actualizados regularmente.',

    # Final CTA
    'cta_title_line1': 'T\u00fa creaste tu empresa.',
    'cta_title_line2': 'Ahora descubre cu\u00e1nto realmente vale.',
    'cta_subtitle': 'Valoraci\u00f3n profesional. Con datos oficiales. En minutos.',
    'cta_button': 'Iniciar valoraci\u00f3n',
    'cta_subtext': 'Sin suscripci\u00f3n \u00b7 Resultados en minutos',

    # Footer
    'footer_desc': 'Valoraci\u00f3n profesional con metodolog\u00eda DCF y benchmarks sectoriales calibrados.',
    'footer_col_product': 'Producto',
    'footer_link_valuation': 'Valoraci\u00f3n DCF',
    'footer_link_pitch': 'Pitch Deck',
    'footer_link_methodology': 'Metodolog\u00eda',
    'footer_link_features': 'Caracter\u00edsticas',
    'footer_col_legal': 'Legal',
    'footer_col_contact': 'Contacto',
    'footer_become_partner': 'Convi\u00e9rtete en Socio',
    'footer_partner_login': 'Login Socio',
    'footer_copyright': '\u00a9 {year} Valuora. Todos los derechos reservados.',

    # Mobile Bar
    'mobile_cta_pitch': 'Crear mi pitch deck',
    'mobile_cta_valuation': 'Iniciar valoraci\u00f3n',

    # Dashboard Page
    'dash_sort_most_recent': 'M\u00e1s reciente',
    'dash_sort_oldest': 'M\u00e1s antiguo',
    'dash_sort_highest_value': 'Mayor valor',
    'dash_sort_lowest_value': 'Menor valor',
    'dash_sort_a_z': 'A \u2192 Z',
    'dash_sort_z_a': 'Z \u2192 A',
    'dash_tip_ke_title': 'El Ke importa',
    'dash_tip_ke_text': 'El costo del patrimonio (Ke) es el principal driver de la valoraci\u00f3n. Peque\u00f1os cambios pueden mover el resultado en millones.',
    'dash_tip_dlom_title': 'DLOM reduce el valor',
    'dash_tip_dlom_text': 'Las empresas privadas reciben un descuento del 10-35% por falta de liquidez. Cuanto m\u00e1s peque\u00f1a y joven la empresa, mayor el descuento.',
    'dash_tip_tv_title': 'Valor Terminal',
    'dash_tip_tv_text': 'En promedio, el 60\u201380% del valor proviene del Valor Terminal. Si este porcentaje es alto, la valoraci\u00f3n depende mucho de supuestos futuros.',
    'dash_tip_multiples_title': 'M\u00faltiplos sectoriales',
    'dash_tip_multiples_text': 'Usa EV/EBITDA y EV/Revenue de tu sector como referencia informativa. En v4 no componen el valor final.',
    'dash_tip_survival_title': 'Supervivencia',
    'dash_tip_survival_text': 'En el modelo v4, la tasa de supervivencia est\u00e1 incorporada directamente en el Valor Terminal \u2014 no es un descuento separado.',
    'dash_tip_keyperson_title': 'Riesgo de Persona Clave',
    'dash_tip_keyperson_text': 'En v4, el riesgo de persona clave est\u00e1 incorporado en Ke como una prima del 0\u20134%. Construye un equipo para reducir este costo.',
    'dash_tip_qualitative_title': 'Puntuaci\u00f3n Cualitativa',
    'dash_tip_qualitative_text': 'Factores como equipo, mercado, producto, tracci\u00f3n y operaciones ajustan \u00b115% del valor. Completa el cuestionario para mayor precisi\u00f3n.',
    'dash_good_morning': 'Buenos d\u00edas',
    'dash_good_afternoon': 'Buenas tardes',
    'dash_good_evening': 'Buenas noches',
    'dash_completed_this_month': 'completados este mes',
    'dash_csv_btn': 'CSV',
    'dash_new_analysis': 'Nuevo an\u00e1lisis',
    'dash_pitch_deck': 'Pitch Deck',
    'dash_filters_title': 'Filtros',
    'dash_search_placeholder': 'Buscar\u2026',
    'dash_all_statuses': 'Todos los estados',
    'dash_status_completed': 'Completado',
    'dash_status_processing': 'Procesando',
    'dash_status_draft': 'Borrador',
    'dash_any_date': 'Cualquier fecha',
    'dash_last_7_days': '\u00daltimos 7 d\u00edas',
    'dash_last_30_days': '\u00daltimos 30 d\u00edas',
    'dash_last_90_days': '\u00daltimos 90 d\u00edas',
    'dash_all_sectors': 'Todos los sectores',
    'dash_any_value': 'Cualquier valor',
    'dash_below_500k': 'Menos de $500K',
    'dash_500k_1m': '$500K \u2013 $1M',
    'dash_1m_5m': '$1M \u2013 $5M',
    'dash_above_5m': 'M\u00e1s de $5M',
    'dash_favorites_only': 'Solo favoritos',
    'dash_view_grid': 'Cuadr\u00edcula',
    'dash_view_list': 'Lista',
    'dash_clear_filters': 'Borrar filtros',
    'dash_monthly_goal': 'Meta mensual',
    'dash_goal_reached': '\u00a1Meta alcanzada!',
    'dash_analysis_created_singular': 'an\u00e1lisis creado',
    'dash_analysis_created_plural': 'an\u00e1lisis creados',
    'dash_max_level': 'Nivel m\u00e1ximo',
    'dash_total_portfolio_value': 'Valor total del portafolio',
    'dash_active_portfolio': 'Portafolio activo',
    'dash_tip_of_the_day': 'Consejo del d\u00eda',
    'dash_latest_analysis': '\u00daltimo an\u00e1lisis',
    'dash_portfolio_evolution': 'Evoluci\u00f3n del Portafolio',
    'dash_analysis_comparator': 'Comparador de An\u00e1lisis',
    'dash_recent_activity': 'Actividad Reciente',
    'dash_my_payments': 'Mis Pagos',
    'dash_hide': 'Ocultar',
    'dash_view_all': 'Ver todo',
    'dash_table_company': 'Empresa',
    'dash_table_plan': 'Plan',
    'dash_table_amount': 'Monto',
    'dash_table_status': 'Estado',
    'dash_table_date': 'Fecha',
    'dash_payment_paid': 'Pagado',
    'dash_payment_pending': 'Pendiente',
    'dash_payment_refunded': 'Reembolsado',
    'dash_payment_failed': 'Fallido',
    'dash_welcome': '\u00a1Bienvenido a Valuora!',
    'dash_welcome_desc': 'Descubre el valor real de tu empresa con an\u00e1lisis profesional basado en DCF y benchmarks sectoriales calibrados.',
    'dash_create_first_analysis': 'Crear mi primer an\u00e1lisis',
    'dash_step_fill_data': 'Rellena los datos',
    'dash_step_fill_desc': 'Ingresos, margen, crecimiento o carga de estados de resultados',
    'dash_step_engine': 'El motor DCF calcula',
    'dash_step_engine_desc': 'DCF + IA procesa en segundos',
    'dash_step_report': 'Obt\u00e9n el reporte',
    'dash_step_report_desc': 'PDF ejecutivo listo para inversores',
    'dash_unlock_report': 'Desbloquear el reporte completo',
    'dash_view_plans': 'Ver planes',
    'dash_time_to_update': 'Hora de actualizar tu valoraci\u00f3n',
    'dash_analysis_found_singular': 'an\u00e1lisis encontrado',
    'dash_analysis_found_plural': 'an\u00e1lisis encontrados',
    'dash_compare_valuations': 'Comparar valoraciones',
    'dash_error_loading': 'Error al cargar an\u00e1lisis.',
    'dash_try_again': 'Intentar de nuevo',
    'dash_create_first_5min': 'Crea tu primera valoraci\u00f3n en 5 minutos',
    'dash_no_analysis_found': 'Ning\u00fan an\u00e1lisis encontrado',
    'dash_awaiting_result': 'Esperando resultado',
    'dash_col_company': 'Empresa',
    'dash_col_sector': 'Sector',
    'dash_col_value': 'Valor',
    'dash_col_status': 'Estado',
    'dash_col_risk': 'Riesgo',
    'dash_col_date': 'Fecha',
    'dash_delete_title': 'Mover a la papelera',
    'dash_delete_message': '"{name}" ser\u00e1 movido a la papelera y eliminado permanentemente despu\u00e9s de 30 d\u00edas.',
    'dash_quick_edit_heading': 'Edici\u00f3n r\u00e1pida',
    'dash_field_company_name': 'Nombre de la empresa',
    'dash_field_annual_revenue': 'Ingreso Anual ($)',
    'dash_field_net_margin': 'Margen Neto (%)',
    'dash_field_ebitda': 'EBITDA ($)',

    # Login Page
    'login_heading': 'Iniciar Sesi\u00f3n',
    'login_subtitle': 'Inicia sesi\u00f3n en tu cuenta para continuar.',
    'login_companies_valued': 'empresas valoradas',
    'login_report_5min': 'Reporte en 5 min',
    'login_sector_benchmarks': 'Benchmarks sectoriales',
    'login_hero_heading': 'Acceso exclusivo para an\u00e1lisis profesional.',
    'login_hero_desc': 'Inicia sesi\u00f3n y accede a tus reportes de valoraci\u00f3n con datos reales.',
    'login_back_to_home': 'Volver al inicio',
    'login_email_label': 'Correo electr\u00f3nico',
    'login_password_label': 'Contrase\u00f1a',
    'login_forgot_password': '\u00bfOlvidaste tu contrase\u00f1a?',
    'login_logging_in': 'Iniciando sesi\u00f3n...',
    'login_submit': 'Iniciar Sesi\u00f3n',
    'login_resend_verification': '\u00bfNo recibiste el email de verificaci\u00f3n? Reenviar',
    'login_no_account': '\u00bfNo tienes una cuenta?',
    'login_create_account': 'Crear cuenta',

    # Register Page
    'reg_heading': 'Crear Cuenta',
    'reg_subtitle': 'Completa tus datos para comenzar.',
    'reg_companies_valued': '500+ empresas valoradas',
    'reg_report_5min': 'Reporte en 5 min',
    'reg_sector_benchmarks': 'Benchmarks sectoriales',
    'reg_hero_heading': 'Crea tu cuenta profesional.',
    'reg_hero_desc': 'Reg\u00edstrate y genera reportes de valoraci\u00f3n en minutos con datos reales.',
    'reg_back_to_home': 'Volver al inicio',
    'reg_referred_by': 'Fuiste referido por',
    'reg_fullname_label': 'Nombre completo',
    'reg_email_label': 'Correo electr\u00f3nico',
    'reg_taxid_label': 'NIF / CIF *',
    'reg_taxid_hint': 'Requerido para procesamiento de pagos',
    'reg_additional_details': 'Detalles adicionales (opcional)',
    'reg_phone_label': 'Tel\u00e9fono',
    'reg_company_label': 'Empresa',
    'reg_password_label': 'Contrase\u00f1a',
    'reg_min_8_chars': 'M\u00ednimo 8 caracteres',
    'reg_has_uppercase': 'Al menos una letra may\u00fascula',
    'reg_has_number': 'Al menos un n\u00famero',
    'reg_strength_label': 'Fortaleza:',
    'reg_confirm_password_label': 'Confirmar Contrase\u00f1a',
    'reg_passwords_no_match': 'Las contrase\u00f1as no coinciden',
    'reg_creating': 'Creando cuenta...',
    'reg_submit': 'Crear Cuenta',
    'reg_agree_prefix': 'Al crear tu cuenta, aceptas los',
    'reg_terms_of_use': 'T\u00e9rminos de Uso',
    'reg_agree_and': 'y la',
    'reg_privacy_policy': 'Pol\u00edtica de Privacidad',
    'reg_have_account': '\u00bfYa tienes una cuenta?',

    # Profile Page
    'profile_heading': 'Mi Perfil',
    'profile_subtitle': 'Administra tu informaci\u00f3n y configuraci\u00f3n de cuenta.',
    'profile_personal_info': 'Informaci\u00f3n Personal',
    'profile_email_label': 'Correo electr\u00f3nico',
    'profile_fullname_label': 'Nombre completo',
    'profile_phone_label': 'Tel\u00e9fono',
    'profile_company_label': 'Empresa',
    'profile_saving': 'Guardando...',
    'profile_save_changes': 'Guardar cambios',
    'profile_change_password': 'Cambiar Contrase\u00f1a',
    'profile_current_pw_label': 'Contrase\u00f1a actual',
    'profile_new_pw_label': 'Nueva contrase\u00f1a',
    'profile_confirm_pw_label': 'Confirmar nueva contrase\u00f1a',
    'profile_changing': 'Cambiando...',
    'profile_change_pw_btn': 'Cambiar contrase\u00f1a',
    'profile_data_privacy': 'Datos y Privacidad',
    'profile_export_title': 'Exportar mis datos',
    'profile_export_desc': 'Descarga todos tus datos personales y an\u00e1lisis en formato JSON.',
    'profile_exporting': 'Exportando...',
    'profile_export_btn': 'Exportar datos',
    'profile_delete_title': 'Eliminar mi cuenta',
    'profile_delete_desc': 'Esta acci\u00f3n es irreversible. Todos tus datos, an\u00e1lisis y pagos ser\u00e1n eliminados permanentemente.',
    'profile_delete_btn': 'Eliminar cuenta permanentemente',
    'profile_delete_dialog_title': '\u00bfEliminar cuenta permanentemente?',
    'profile_delete_dialog_msg': 'Todos tus datos, an\u00e1lisis y pagos ser\u00e1n eliminados permanentemente. Esta acci\u00f3n NO se puede deshacer.',
    'profile_delete_dialog_confirm': 'S\u00ed, eliminar mi cuenta',
}

# Now reconstruct the file using en.js structure but replacing values with ES translations
lines = en_content.split('\n')
out_lines = []

for line in lines:
    # Replace header comment
    if line.strip() == '* English (US) translations \u2014 default language':
        out_lines.append(' * Espa\u00f1ol (ES) translations')
        continue

    # Check if this is a key-value line
    m = re.match(r'^(\s+)(\w+):\s', line)
    if m:
        indent = m.group(1)
        key = m.group(2)
        if key in ES:
            val = ES[key]
            # Escape single quotes in value
            escaped = val.replace("'", "\\'")
            out_lines.append(f"{indent}{key}: '{escaped}',")
        else:
            # Keep en.js value as fallback
            out_lines.append(line)
    else:
        out_lines.append(line)

result = '\n'.join(out_lines)

path = 'frontend/src/lib/i18n/es.js'
with open(path, 'w') as f:
    f.write(result)

# Verify
keys_out = re.findall(r'^\s+(\w+):', result, re.MULTILINE)
print(f'Written es.js with {len(keys_out)} keys')
