#!/usr/bin/env python3
"""Generate complete pt.js from en.js structure with Portuguese translations."""

import re

with open('frontend/src/lib/i18n/en.js', 'r') as f:
    en_content = f.read()

PT = {
    # Common
    'app_name': 'Valuora',
    'tagline': 'Valua\u00e7\u00e3o Empresarial Profissional',
    'loading': 'Carregando...',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'delete': 'Excluir',
    'confirm': 'Confirmar',
    'back': 'Voltar',
    'next': 'Pr\u00f3ximo',
    'close': 'Fechar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'export': 'Exportar',
    'download': 'Baixar',
    'submit': 'Enviar',
    'edit': 'Editar',
    'view': 'Ver',
    'copy': 'Copiar',
    'share': 'Compartilhar',
    'yes': 'Sim',
    'no': 'N\u00e3o',
    'or': 'ou',
    'of': 'de',
    'error': 'Erro',
    'success': 'Sucesso',

    # Auth
    'login': 'Entrar',
    'register': 'Cadastrar',
    'logout': 'Sair',
    'email': 'E-mail',
    'password': 'Senha',
    'confirm_password': 'Confirmar Senha',
    'full_name': 'Nome Completo',
    'forgot_password': 'Esqueceu sua senha?',
    'reset_password': 'Redefinir Senha',
    'verify_email': 'Verificar E-mail',
    'already_have_account': 'J\u00e1 tem uma conta?',
    'dont_have_account': 'N\u00e3o tem uma conta?',
    'create_account': 'Criar Conta',
    'login_success': 'Login realizado com sucesso',
    'register_success': 'Conta criada! Verifique seu e-mail.',

    # Navigation
    'nav_dashboard': 'Painel',
    'nav_new_analysis': 'Nova Valua\u00e7\u00e3o',
    'nav_simulator': 'Simulador',
    'nav_compare': 'Comparar',
    'nav_wacc_calculator': 'Calculadora WACC',
    'nav_inverse_projection': 'Proje\u00e7\u00e3o Inversa',
    'nav_pitch_deck': 'Pitch Deck',
    'nav_trash': 'Lixeira',
    'nav_profile': 'Perfil',
    'nav_notifications': 'Notifica\u00e7\u00f5es',
    'nav_partner': 'Parceiro',
    'nav_admin': 'Administrador',

    # Dashboard
    'dashboard_title': 'Minhas Valua\u00e7\u00f5es',
    'dashboard_empty': 'Voc\u00ea ainda n\u00e3o tem valua\u00e7\u00f5es. Crie a primeira!',
    'dashboard_new_analysis': 'Nova Valua\u00e7\u00e3o',
    'dashboard_total_analyses': 'Total de An\u00e1lises',
    'dashboard_completed': 'Conclu\u00eddas',

    # Analysis
    'analysis_company_name': 'Nome da Empresa',
    'analysis_sector': 'Setor',
    'analysis_revenue': 'Receita Anual',
    'analysis_net_margin': 'Margem L\u00edquida',
    'analysis_growth_rate': 'Taxa de Crescimento',
    'analysis_debt': 'D\u00edvida Total',
    'analysis_cash': 'Caixa e Equivalentes',
    'analysis_founder_dependency': 'Depend\u00eancia do Fundador',
    'analysis_projection_years': 'Anos de Proje\u00e7\u00e3o',
    'analysis_ebitda': 'EBITDA',
    'analysis_employees': 'N\u00famero de Funcion\u00e1rios',
    'analysis_years_in_business': 'Anos de Opera\u00e7\u00e3o',
    'analysis_equity_value': 'Valor Patrimonial',
    'analysis_risk_score': 'Pontua\u00e7\u00e3o de Risco',
    'analysis_maturity_index': '\u00cdndice de Maturidade',
    'analysis_create': 'Criar An\u00e1lise',
    'analysis_processing': 'Processando sua valua\u00e7\u00e3o...',
    'analysis_completed': 'Valua\u00e7\u00e3o Conclu\u00edda',
    'analysis_failed': 'Valua\u00e7\u00e3o Falhou',

    # Plans
    'plan_professional': 'Valua\u00e7\u00e3o Profissional',
    'plan_professional_desc': 'M\u00e9todos DCF + Scorecard + Checklist com relat\u00f3rio b\u00e1sico',
    'plan_investor_ready': 'Valua\u00e7\u00e3o Avan\u00e7ada',
    'plan_investor_ready_desc': 'Os 6 m\u00e9todos + relat\u00f3rio completo + simulador + benchmarks',
    'plan_fundraising': 'Valua\u00e7\u00e3o Completa',
    'plan_fundraising_desc': 'Tudo incluso + an\u00e1lise IA + roadmap + suporte priorit\u00e1rio',
    'plan_price_professional': 'R$ 990',
    'plan_price_investor_ready': 'R$ 2.490',
    'plan_price_fundraising': 'R$ 4.990',
    'plan_one_time': 'pagamento \u00fanico',
    'plan_select': 'Selecionar Plano',
    'plan_most_popular': 'Mais Popular',

    # Valuation Methods
    'method_dcf': 'Fluxo de Caixa Descontado (DCF)',
    'method_scorecard': 'M\u00e9todo Scorecard',
    'method_checklist': 'M\u00e9todo Checklist / Berkus',
    'method_venture_capital': 'M\u00e9todo de Venture Capital',
    'method_multiples': 'M\u00faltiplos de Comparables',
    'method_all': 'Resumo de Todos os M\u00e9todos',

    # Reports
    'report_download': 'Baixar Relat\u00f3rio',
    'report_generating': 'Gerando relat\u00f3rio...',
    'report_ready': 'Relat\u00f3rio Pronto',
    'report_pages': '25+ p\u00e1ginas',

    # Payment
    'payment_title': 'Pagamento',
    'payment_processing': 'Processando pagamento...',
    'payment_success': 'Pagamento confirmado!',
    'payment_failed': 'Pagamento falhou',
    'payment_history': 'Hist\u00f3rico de Pagamentos',
    'payment_amount': 'Valor',
    'payment_status': 'Status',
    'payment_date': 'Data',
    'payment_method': 'M\u00e9todo',

    # Partner
    'partner_dashboard': 'Painel do Parceiro',
    'partner_clients': 'Clientes',
    'partner_commissions': 'Comiss\u00f5es',
    'partner_finance': 'Finan\u00e7as',
    'partner_marketing': 'Marketing',
    'partner_referral_link': 'Link de Indica\u00e7\u00e3o',

    # Footer
    'footer_privacy': 'Pol\u00edtica de Privacidade',
    'footer_terms': 'Termos de Uso',
    'footer_contact': 'Contato',
    'footer_rights': '\u00a9 {year} Valuora. Todos os direitos reservados.',

    # Landing Page - Legacy
    'hero_title': 'Saiba o Valor Real da Sua Empresa',
    'hero_subtitle': 'Valua\u00e7\u00e3o empresarial profissional com 6 m\u00e9todos comprovados. Receba seu relat\u00f3rio executivo em minutos.',
    'hero_cta': 'Iniciar Valua\u00e7\u00e3o',
    'hero_secondary_cta': 'Diagn\u00f3stico Gratuito',
    'hero_trusted_by': 'Mais de {count}+ empresas confiam em n\u00f3s',

    'features_title': 'Por que escolher a Valuora?',
    'feature_dcf': 'Valua\u00e7\u00e3o DCF',
    'feature_dcf_desc': 'An\u00e1lise de Fluxo de Caixa Descontado com dados Damodaran e taxas reais de mercado.',
    'feature_multi_method': '6 M\u00e9todos de Valua\u00e7\u00e3o',
    'feature_multi_method_desc': 'DCF, Scorecard, Checklist, M\u00e9todo VC, M\u00faltiplos e An\u00e1lise IA.',
    'feature_report': 'Relat\u00f3rio Executivo',
    'feature_report_desc': 'Relat\u00f3rio profissional de 25+ p\u00e1ginas com gr\u00e1ficos, an\u00e1lises e recomenda\u00e7\u00f5es.',
    'feature_fast': 'Resultados em Minutos',
    'feature_fast_desc': 'O que consultores levam semanas, a Valuora entrega em minutos.',

    'pricing_title': 'Pre\u00e7os Simples e Transparentes',
    'pricing_subtitle': 'Pagamento \u00fanico. Sem assinaturas.',

    'faq_title': 'Perguntas Frequentes',

    # Errors
    'error_network': 'Erro de rede. Verifique sua conex\u00e3o.',
    'error_unauthorized': 'Sess\u00e3o expirada. Fa\u00e7a login novamente.',
    'error_not_found': 'P\u00e1gina n\u00e3o encontrada.',
    'error_server': 'Erro no servidor. Tente novamente mais tarde.',
    'error_validation': 'Por favor verifique os campos do formul\u00e1rio.',

    # Pages Common
    'financial_data': 'Dados Financeiros',
    'restore': 'Restaurar',
    'resend': 'Reenviar',
    'deactivate': 'Desativar',
    'activate': 'Ativar',
    'copied': 'Copiado!',
    'mark_paid': 'Marcar Pago',
    'paid': 'Pago',
    'optional': '(opcional)',
    'verified': 'Verificados',
    'unverified': 'N\u00e3o verificados',
    'administration': 'Administra\u00e7\u00e3o',
    'partner_mode': 'Modo Parceiro',
    'view_result': 'Ver Resultado',
    'solution_found': 'Solu\u00e7\u00e3o encontrada',
    'minimum_pct': 'M\u00ednimo (%)',
    'maximum_pct': 'M\u00e1ximo (%)',
    'simulated': 'simulado',
    'net_income': 'lucro l\u00edquido',
    'consulting_firm': 'Consultoria / Firma',

    # Validation
    'name_cannot_be_empty': 'O nome n\u00e3o pode estar vazio.',
    'action_cannot_be_undone': 'Esta a\u00e7\u00e3o n\u00e3o pode ser desfeita.',
    'analysis_not_found': 'An\u00e1lise n\u00e3o encontrada.',
    'page_not_found': 'P\u00e1gina n\u00e3o encontrada',
    'page_not_found_desc': 'A p\u00e1gina que voc\u00ea procura n\u00e3o existe ou foi movida.',
    'go_home': 'Ir para o In\u00edcio',

    # Admin
    'max_uses_hint': 'M\u00e1x. usos (vazio = ilimitado)',
    'expiration_hint': 'Expira\u00e7\u00e3o (vazio = sem expira\u00e7\u00e3o)',

    # Partner Extra
    'utm_link_copied': 'Link UTM copiado!',
    'no_notes_hint': 'Sem notas. Clique em editar para adicionar.',

    # Trash
    'trash_title': 'Lixeira',
    'items_in_trash': '{count} {items} na lixeira',
    'item_singular': 'item',
    'item_plural': 'itens',

    # Simulator
    'simulator_title': 'Simulador \u2014 {name}',
    'equity_value_simulated': 'Valor Patrimonial (simulado)',

    # Analysis Page
    'position_vs_sector': 'Posi\u00e7\u00e3o vs Faixa Setorial (P25 \u2013 P75)',

    # Onboarding
    'onboarding_nav_hint': 'Esc para fechar \u00b7 \u2190 \u2192 para navegar',

    # Partner Marketing
    'sales_greeting_1': 'Tudo bem?',
    'sales_intro': 'Meu nome \u00e9 [Seu Nome], sou da [Sua Firma].',
    'sales_greeting_2': 'S\u00f3 passando para dar um al\u00f4',
    'sales_greeting_3': 'Como voc\u00ea est\u00e1?',
    'sales_placeholder_name': '[Nome]',
    'sales_placeholder_your_name': '[Seu Nome]',
    'sales_and': 'e',

    # Extra UI
    'go_dashboard': 'Ir para o Painel',
    'home_page': 'P\u00e1gina Inicial',
    'reanalyze': 'Re-analisar',
    'reanalyzing': 'Re-analisando\u2026',
    'profile_updated': 'Perfil atualizado',
    'all_filter': 'Todos',
    'active_filter': 'Ativos',
    'inactive_filter': 'Inativos',
    'active_status': 'Ativo',
    'inactive_status': 'Inativo',
    'leave_blank_to_clear': 'Deixe em branco para limpar',
    'code_label': 'C\u00f3digo',
    'description_label': 'Descri\u00e7\u00e3o',
    'internal_use': 'Uso interno',
    'day_singular': 'dia',
    'day_plural': 'dias',
    'dismiss': 'Dispensar',
    'next_goal': 'Pr\u00f3xima meta',
    'all_goals_reached': 'Todas as metas alcan\u00e7adas!',
    'goals': 'metas',
    'source_label': 'Fonte',
    'medium_label': 'M\u00eddio',
    'campaign_label': 'Campanha',
    'refund': 'Reembolsar',
    'new_clients_singular': 'novo cliente!',
    'new_clients_plural': 'novos clientes!',
    'actions': 'A\u00e7\u00f5es',
    'verified_badge': 'verificado',
    'verify_email_action': 'Verificar email',
    'adjust_params': 'Ajuste par\u00e2metros e recalcule em tempo real',
    'calculating': 'Calculando...',
    'calculate': 'Calcular',
    'notifications': 'Notifica\u00e7\u00f5es',
    'mark_all_read': 'Marcar tudo como lido',
    'mark_as_read': 'Marcar como lido',
    'no_notifications': 'Sem notifica\u00e7\u00f5es',
    'min_label': 'M\u00ednimo',
    'max_label': 'M\u00e1ximo',
    'see_result': 'Ver Resultado',
    'position_vs_range': 'Posi\u00e7\u00e3o vs Faixa Setorial',
    'sign_in': 'Entrar',

    # Notifications Page
    'track_recent_events': 'Acompanhe seus eventos recentes',
    'filter_all': 'Todos',
    'filter_analyses': 'An\u00e1lises',
    'filter_payments': 'Pagamentos',
    'filter_pitchdeck': 'Pitch Deck',
    'nothing_here_yet': 'Nada aqui ainda.',
    'previous': 'Anterior',

    # Sidebar
    'nav_overview': 'Vis\u00e3o Geral',
    'nav_clients': 'Clientes',
    'nav_commissions': 'Comiss\u00f5es',
    'nav_finance': 'Finan\u00e7as',
    'nav_marketing': 'Marketing',
    'sidebar_processing': 'processando',
    'sidebar_partner_section': 'Parceiro',
    'sidebar_portfolio': 'Portf\u00f3lio',
    'sidebar_completed': 'Conclu\u00eddos',
    'sidebar_highest': 'Maior',
    'sidebar_log_out': 'Sair',
    'sidebar_user_fallback': 'Usu\u00e1rio',

    # Landing Navbar
    'nav_how_it_works': 'Como funciona',
    'nav_features': 'Recursos',
    'nav_plans': 'Planos',
    'nav_methodology': 'Metodologia',
    'nav_partners': 'Parceiros',
    'nav_sign_in': 'Entrar',
    'nav_start_valuation': 'INICIAR VALUA\u00c7\u00c3O',
    'nav_login_partner': 'Login Parceiro',

    # Sticky Bar
    'sticky_valuation_from': 'Valua\u00e7\u00e3o a partir de R$ 990',
    'sticky_pitch_deck_price': 'Pitch Deck R$ 897',
    'sticky_one_time': 'Pagamento \u00fanico',
    'sticky_start': 'Iniciar \u2192',

    # Hero
    'hero_valuation_dcf': 'Valua\u00e7\u00e3o DCF',
    'hero_pitch_deck': 'Pitch Deck',
    'hero_new_badge': 'NOVO',
    'hero_how_much_is': 'Quanto vale',
    'hero_your_company_worth': 'a sua empresa?',
    'hero_val_subtitle': 'Valua\u00e7\u00e3o profissional em minutos \u2014 n\u00e3o semanas. O rigor do DCF com interpreta\u00e7\u00e3o de IA, benchmarks setoriais calibrados e o mesmo padr\u00e3o M&A a uma fra\u00e7\u00e3o do custo.',
    'hero_val_badge_dcf': 'Motor DCF Institucional',
    'hero_val_badge_ai': 'An\u00e1lise com Intelig\u00eancia Artificial',
    'hero_val_badge_report': 'Relat\u00f3rio de at\u00e9 25 p\u00e1ginas',
    'hero_val_cta_start': 'Iniciar valua\u00e7\u00e3o',
    'hero_val_cta_diagnostic': 'Diagn\u00f3stico Gratuito',
    'hero_val_subtext': 'Sem assinatura \u00b7 Resultados em minutos \u00b7 A partir de R$ 990',
    'hero_val_report_samples': 'Amostras de relat\u00f3rios',
    'hero_val_sample_professional': 'Valua\u00e7\u00e3o Profissional',
    'hero_val_sample_advanced': 'Valua\u00e7\u00e3o Avan\u00e7ada',
    'hero_val_sample_complete': 'Valua\u00e7\u00e3o Completa \u2605',
    'hero_pitch_subtitle': 'Pitch deck profissional para investidores \u2014 em minutos. Design paisagem A4 com narrativa IA, painel KPI, gr\u00e1ficos de cen\u00e1rios, TAM/SAM/SOM visual e matriz competitiva.',
    'hero_pitch_badge_ai': 'Narrativa IA',
    'hero_pitch_badge_waterfall': 'Waterfall + 3 Cen\u00e1rios',
    'hero_pitch_badge_tam': 'TAM/SAM/SOM Visual',
    'hero_pitch_badge_design': 'A4 Paisagem \u2014 Design Premium',
    'hero_pitch_cta_create': 'Criar meu pitch deck',
    'hero_pitch_cta_see_dcf': 'Ver Valua\u00e7\u00e3o DCF',
    'hero_pitch_subtext': 'Sem assinatura \u00b7 Resultados em minutos \u00b7 R$ 897 pagamento \u00fanico',
    'hero_pitch_sample_title': 'Amostra de pitch deck',
    'hero_pitch_view_pdf': 'Ver PDF completo \u2197',

    # Trust Badges
    'trust_data_protection': 'Prote\u00e7\u00e3o de Dados',
    'trust_ssl': 'SSL 256-bit',
    'trust_dcf': 'Metodologia DCF',
    'trust_benchmarks': 'Benchmarks Setoriais',

    # Mock Preview
    'mock_pitch_label': 'Pitch Deck \u00b7 Empresa X',
    'mock_pitch_round': 'Rodada S\u00e9rie A \u2014 R$ 5M',
    'mock_pitch_slides': '12 slides',
    'mock_market_size': 'Tamanho de Mercado',
    'mock_tam_total': 'Total',
    'mock_sam_addressable': 'Endere\u00e7\u00e1vel',
    'mock_som_obtainable': 'Alcan\u00e7\u00e1vel',
    'mock_val_equity_label': 'Valor Patrimonial Estimado',
    'mock_val_range': 'Faixa: R$ 3.1M \u2014 R$ 5.6M',
    'mock_val_risk_score': 'Pontua\u00e7\u00e3o de Risco',
    'mock_val_maturity': 'Maturidade',
    'mock_val_percentile': 'Percentil',
    'mock_val_fcfe_proj': 'Proje\u00e7\u00e3o FCFE \u2014 5 anos',
    'badge_ai_narrative': 'Narrativa IA',
    'badge_tam_sam_som': 'TAM/SAM/SOM',
    'badge_kpi_panel': 'Painel KPI',
    'badge_dcf_gordon': 'DCF Gordon',
    'badge_sector_benchmark': 'Benchmark Setorial',
    'badge_5yr_projection': 'Proje\u00e7\u00e3o 5 anos',
    'badge_ai_analysis': 'An\u00e1lise IA',
    'mock_open': 'Abrir \u2197',

    # Engine Strip
    'strip_engine_active': 'Motor DCF v7 \u2014 Ativo',
    'strip_updated_on': 'Atualizado em',
    'strip_treasury': 'Treasury 10Y:',
    'strip_beta_damodaran': 'Beta Damodaran',
    'strip_sectors': 'setores industriais calibrados',

    # Credibility
    'cred_title': 'Metodologia reconhecida pelo mercado',
    'cred_ssl': 'Criptografia SSL 256-bit',
    'cred_certified_dcf': 'DCF Certificado',
    'cred_benchmarks': 'Benchmarks Setoriais',
    'cred_damodaran': 'Beta Damodaran / NYU Stern',

    # Comparison Table
    'compare_label': 'Compara\u00e7\u00e3o',
    'compare_title_why': 'Por que a',
    'compare_title_different': '\u00e9 diferente?',
    'compare_traditional': 'Consultoria Tradicional',
    'compare_time': 'Tempo',
    'compare_time_qv': 'Resultado em 5 minutos',
    'compare_time_cons': 'Semanas a meses',
    'compare_cost': 'Custo',
    'compare_cost_qv': 'A partir de R$ 990',
    'compare_cost_cons': 'De R$ 5.000 a R$ 50.000+',
    'compare_complexity': 'Complexidade',
    'compare_complexity_qv': 'Preencha e receba \u2014 simples',
    'compare_complexity_cons': 'Reuni\u00f5es, entrevistas, planilhas',
    'compare_report': 'Relat\u00f3rio PDF',
    'compare_report_qv': 'At\u00e9 25 p\u00e1ginas inclusas',
    'compare_report_cons': 'Cobrado \u00e0 parte ou n\u00e3o incluso',
    'compare_available': 'Dispon\u00edvel',
    'compare_available_qv': '24/7, de qualquer lugar',
    'compare_available_cons': 'Hor\u00e1rio comercial, presencial',
    'compare_cta': 'Come\u00e7ar agora \u2014 gr\u00e1tis',

    # Problem / Solution
    'problem_label': 'O problema',
    'problem_title': 'Sem uma valua\u00e7\u00e3o estruturada, qualquer negocia\u00e7\u00e3o come\u00e7a com',
    'problem_asymmetry': 'assimetria de informa\u00e7\u00e3o',
    'problem_case_stake': 'Venda de participa\u00e7\u00e3o',
    'problem_case_partner': 'Entrada de s\u00f3cio',
    'problem_case_fundraising': 'Capta\u00e7\u00e3o de investimento',
    'problem_case_exit': 'Planejamento de sa\u00edda',
    'problem_desc': 'Consultorias tradicionais levam semanas e cobram entre R$ 5.000 e R$ 50.000. A Valuora entrega uma an\u00e1lise t\u00e9cnica, fundamentada e documentada em minutos.',
    'solution_label': 'A solu\u00e7\u00e3o',
    'solution_engine_title': 'Motor Institucional',
    'solution_engine_desc': 'DCF com FCFE projetado a 10 anos, WACC, beta setorial Damodaran e taxa livre de risco do Tesouro dos EUA \u2014 a mesma metodologia utilizada por consultorias de M&A.',
    'solution_engine_tag': 'Motor DCF v7',
    'solution_bench_title': 'Benchmarks Setoriais',
    'solution_bench_desc': 'Base de dados propriet\u00e1ria com mais de 50 segmentos industriais, calibrada com metodologia Damodaran e dados de mercado. Sua valua\u00e7\u00e3o reflete o cen\u00e1rio real do seu setor.',
    'solution_bench_tag': 'Base de Dados Setorial',
    'solution_report_title': 'Relat\u00f3rio Defens\u00e1vel',
    'solution_report_desc': 'At\u00e9 25 p\u00e1ginas com metodologia de c\u00e1lculo, premissas, cen\u00e1rios e an\u00e1lise IA \u2014 pronto para investidores, s\u00f3cios ou bancos.',
    'solution_report_tag': 'PDF Premium',

    # Use Cases
    'use_cases_label': 'Casos de uso',
    'use_cases_title_prefix': 'Feito para quem precisa de',
    'use_cases_title_highlight': 'respostas concretas',
    'use_case_sell_title': 'Dono de neg\u00f3cio que quer vender',
    'use_case_sell_desc': 'Saiba exatamente quanto pedir antes de iniciar qualquer negocia\u00e7\u00e3o de venda.',
    'use_case_raise_title': 'Startup captando investimento',
    'use_case_raise_desc': 'Apresente uma valua\u00e7\u00e3o profissional e defens\u00e1vel para investidores e fundos.',
    'use_case_accounting_title': 'Contabilidade / Consultoria',
    'use_case_accounting_desc': 'Ofere\u00e7a valua\u00e7\u00e3o como servi\u00e7o adicional aos seus clientes. Torne-se parceiro.',
    'use_case_buy_title': 'Buscando comprar',
    'use_case_buy_desc': 'Avalie a empresa-alvo antes de fazer uma oferta e negocie com dados reais.',

    # How It Works
    'hiw_label': 'Como funciona',
    'hiw_title': '4 passos para sua valua\u00e7\u00e3o',
    'hiw_step1_title': 'Crie sua conta',
    'hiw_step1_desc': 'Cadastro com confirma\u00e7\u00e3o por e-mail. Ambiente seguro.',
    'hiw_step2_title': 'Envie seus dados financeiros',
    'hiw_step2_desc': 'Entrada manual ou upload de DRE em PDF/Excel. A IA extrai e estrutura automaticamente.',
    'hiw_step3_title': 'Veja a pr\u00e9via',
    'hiw_step3_desc': 'Receba indicadores-chave antes de desbloquear o relat\u00f3rio.',
    'hiw_step4_title': 'Desbloqueie o relat\u00f3rio completo',
    'hiw_step4_desc': 'Escolha o plano e receba o PDF executivo por e-mail.',

    # Before / After
    'transform_label': 'Transforma\u00e7\u00e3o',
    'transform_title_prefix': 'Do jeito antigo para o',
    'transform_title_highlight': 'jeito certo',
    'transform_subtitle': 'A mesma qualidade das melhores consultorias \u2014 sem as semanas de espera e sem o custo proibitivo.',
    'before_tag': 'ANTES \u2014 Consultoria Tradicional',
    'before_timeframe': 'Prazo',
    'before_timeframe_val': '3 a 8 semanas',
    'before_cost_val': 'De R$ 5.000 a R$ 50.000',
    'before_process': 'Processo',
    'before_process_val': 'Reuni\u00f5es, entrevistas, aprova\u00e7\u00f5es',
    'before_delivery': 'Entrega',
    'before_delivery_val': 'PDF gen\u00e9rico, sem an\u00e1lise contextual',
    'before_availability': 'Disponibilidade',
    'before_availability_val': 'Hor\u00e1rio comercial, presencial',
    'after_tag': 'AGORA \u2014 Valuora',
    'after_timeframe_val': 'Resultado em 5 minutos',
    'after_cost_val': 'A partir de R$ 990, pagamento \u00fanico',
    'after_process_val': 'Preencha o formul\u00e1rio. Pronto.',
    'after_delivery_val': 'At\u00e9 25 p\u00e1ginas com an\u00e1lise estrat\u00e9gica IA',
    'after_availability_val': '24/7, qualquer dispositivo',

    # Products
    'products_label': 'Nossos produtos',
    'products_title': 'Duas ferramentas para avaliar e apresentar sua empresa',
    'products_subtitle': 'Valua\u00e7\u00e3o profissional e pitch deck para investidores \u2014 tudo em uma s\u00f3 plataforma.',
    'products_val_core': 'CORE',
    'products_val_title': 'Valua\u00e7\u00e3o DCF',
    'products_val_sub': 'Motor institucional + IA',
    'products_val_desc': 'Relat\u00f3rio profissional de at\u00e9 25 p\u00e1ginas com DCF, benchmark setorial calibrado, an\u00e1lise de risco, simulador estrat\u00e9gico e narrativa IA.',
    'products_val_feat_dcf': 'DCF Gordon + Exit Multiple',
    'products_val_feat_bench': 'Benchmark Setorial',
    'products_val_feat_ai': 'An\u00e1lise IA',
    'products_val_feat_pages': 'At\u00e9 25 p\u00e1ginas',
    'products_val_cta_start': 'Iniciar',
    'products_pitch_new': 'NOVO',
    'products_pitch_title': 'Pitch Deck',
    'products_pitch_sub': 'PDF pronto para investidores',
    'products_pitch_desc': 'A4 paisagem premium com TAM/SAM/SOM visual, matriz competitiva 2\u00d72, waterfall de receitas, painel KPI, 3 cen\u00e1rios financeiros, equipe com fotos e narrativa IA.',
    'products_pitch_feat_a4': 'A4 Paisagem',
    'products_pitch_feat_tam': 'TAM/SAM/SOM Visual',
    'products_pitch_feat_matrix': 'Matriz 2\u00d72',
    'products_pitch_feat_waterfall': 'Waterfall + Cen\u00e1rios',
    'products_pitch_feat_kpi': 'Painel KPI',
    'products_pitch_feat_ai': 'Narrativa IA',
    'products_pitch_one_time': '/ pagamento \u00fanico',
    'products_pitch_cta': 'Criar',
    'products_pitch_view_sample': 'Ver amostra de pitch deck',

    # Features Section
    'features_label': 'Recursos',
    'features_title_full': 'Tudo para avaliar e defender o valor da sua empresa',
    'feat_dcf_title': 'Valua\u00e7\u00e3o DCF Completa',
    'feat_dcf_desc': 'Valor estimado com DCF Gordon + Exit Multiple, DLOM e an\u00e1lise de sobreviv\u00eancia.',
    'feat_pdf_title': 'Relat\u00f3rio PDF Premium',
    'feat_pdf_desc': 'Documento institucional com gr\u00e1ficos, proje\u00e7\u00f5es, benchmark e an\u00e1lise estrat\u00e9gica IA.',
    'feat_sim_title': 'Simulador Interativo',
    'feat_sim_desc': 'Altere crescimento, margem e taxa de desconto. A valua\u00e7\u00e3o recalcula na hora.',
    'feat_ai_title': 'An\u00e1lise Estrat\u00e9gica IA',
    'feat_ai_desc': 'An\u00e1lise narrativa com recomenda\u00e7\u00f5es estrat\u00e9gicas geradas por intelig\u00eancia artificial.',
    'feat_compare_title': 'Comparar An\u00e1lises',
    'feat_compare_desc': 'Compare at\u00e9 4 empresas lado a lado \u2014 valua\u00e7\u00e3o, risco, receita e m\u00faltiplos em um s\u00f3 painel.',
    'feat_bench_title': 'Benchmark Estrat\u00e9gico',
    'feat_bench_desc': 'Descubra se sua margem, crescimento e efici\u00eancia est\u00e3o acima ou abaixo do mercado.',
    'feat_cta_start_free': 'Come\u00e7ar gr\u00e1tis',

    # Methodology
    'method_label': 'Metodologia',
    'method_title_full': '6 camadas de an\u00e1lise para uma valua\u00e7\u00e3o defens\u00e1vel',
    'method_subtitle': 'Combinamos tr\u00eas m\u00e9todos de valua\u00e7\u00e3o com tr\u00eas camadas de ajuste \u2014 o mesmo enfoque utilizado por consultorias de M&A.',
    'method_gordon_title': 'DCF \u2014 Crescimento Gordon',
    'method_gordon_badge': 'Peso por maturidade',
    'method_gordon_desc': 'Projeta FCFE (fluxo ao patrim\u00f4nio) a 10 anos e calcula o Valor Terminal usando a f\u00f3rmula de Gordon. Usa Ke (Valuora) como taxa de desconto, com beta setorial Damodaran e taxa livre de risco do Tesouro dos EUA.',
    'method_gordon_tags': 'FCFE Projetado \u00b7 Valor Terminal \u00b7 Ke \u00b7 Beta Valuora',
    'method_exit_title': 'DCF \u2014 Exit Multiple',
    'method_exit_desc': 'Mesmo fluxo de caixa projetado, mas o Valor Terminal \u00e9 calculado aplicando um m\u00faltiplo EV/EBITDA setorial ao EBITDA do \u00faltimo ano projetado. Reduz a depend\u00eancia de premissas de crescimento perp\u00e9tuo.',
    'method_exit_tags': 'EV/EBITDA \u00b7 Valor Terminal \u00b7 Exit multiple \u00b7 EBITDA Projetado',
    'method_multiples_title': 'M\u00faltiplos Setoriais',
    'method_multiples_badge': 'Informativo',
    'method_multiples_desc': 'Valua\u00e7\u00e3o informativa por EV/Revenue e EV/EBITDA setorial, com dados reais de Damodaran/NYU Stern. Na v4, os m\u00faltiplos n\u00e3o comp\u00f5em o valor final.',
    'method_dlom_title': 'DLOM',
    'method_dlom_badge': '10\u201335%',
    'method_dlom_desc': 'Desconto de 10% a 35% para empresas privadas (sem liquidez de mercado). Ajustado por tamanho, maturidade e liquidez do setor.',
    'method_dlom_tags': 'Desconto por Falta de Comerciabilidade \u00b7 Privadas',
    'method_survival_title': 'Taxa de Sobreviv\u00eancia',
    'method_survival_badge': 'BLS',
    'method_survival_desc': 'Desconto baseado na probabilidade real de sobreviv\u00eancia da empresa no horizonte de proje\u00e7\u00e3o, com dados BLS/SBA e bonifica\u00e7\u00e3o por anos de opera\u00e7\u00e3o.',
    'method_survival_tags': 'Probabilidade real \u00b7 Horizonte de proje\u00e7\u00e3o',
    'method_qual_title': 'Pontua\u00e7\u00e3o Qualitativa',
    'method_qual_badge': '\u00b115%',
    'method_qual_desc': 'Avalia\u00e7\u00e3o de equipe, mercado, produto, tra\u00e7\u00e3o e opera\u00e7\u00f5es. Ajusta \u00b115% do valor final conforme fatores de risco n\u00e3o financeiros.',
    'method_qual_tags': '10 perguntas \u00b7 5 dimens\u00f5es \u00b7 Fatores n\u00e3o financeiros',
    'method_ai_title': 'QV Intelligence',
    'method_ai_badge': 'IA Propriet\u00e1ria',
    'method_ai_desc': 'Depois que o motor DCF calcula todos os n\u00fameros, QV Intelligence interpreta os resultados. Contextualiza a valua\u00e7\u00e3o no seu setor, aponta inconsist\u00eancias, compara com benchmarks de mercado e redige o Resumo Executivo.',
    'method_ai_tags': 'QV Intelligence \u00b7 Resumo Executivo \u00b7 Contexto setorial \u00b7 An\u00e1lise de risco',
    'pipeline_result': 'Resultado: uma valua\u00e7\u00e3o t\u00e9cnica, consistente e defens\u00e1vel.',

    # Plans / Pricing
    'plans_label': 'Pre\u00e7os',
    'plans_title_full': 'Pagamento \u00fanico. Sem assinatura.',
    'plans_stripe': 'Pagamento seguro via Stripe',
    'plan_pro_name': 'Valua\u00e7\u00e3o Profissional',
    'plan_pro_desc': 'Valua\u00e7\u00e3o DCF Completa',
    'plan_pro_pages': '~8 p\u00e1ginas',
    'plan_pro_f1': 'Valua\u00e7\u00e3o DCF Crescimento Gordon',
    'plan_pro_f2': 'Pontua\u00e7\u00e3o de risco e maturidade',
    'plan_pro_f3': 'Cen\u00e1rios conservador / base / otimista',
    'plan_pro_f4': 'Relat\u00f3rio executivo b\u00e1sico',
    'plan_pro_f5': 'Entrega por e-mail',
    'plan_adv_name': 'Valua\u00e7\u00e3o Avan\u00e7ada',
    'plan_adv_desc': 'An\u00e1lise completa com benchmark',
    'plan_adv_pages': '~15 p\u00e1ginas',
    'plan_adv_f1': 'Tudo da Valua\u00e7\u00e3o Profissional',
    'plan_adv_f2': 'DCF Exit Multiple + M\u00faltiplos',
    'plan_adv_f3': 'Benchmark setorial oficial',
    'plan_adv_f4': 'DLOM + Sobreviv\u00eancia + DRE',
    'plan_adv_f5': 'Proje\u00e7\u00e3o de Receita e FCFE',
    'plan_adv_f6': 'Tabela de sensibilidade',
    'plan_adv_f7': 'Pr\u00eamio de controle / desconto minorit\u00e1rio',
    'plan_comp_name': 'Valua\u00e7\u00e3o Completa',
    'plan_comp_desc': 'N\u00edvel m\u00e1ximo de an\u00e1lise',
    'plan_comp_pages': '~25 p\u00e1ginas',
    'plan_comp_f1': 'Tudo da Valua\u00e7\u00e3o Avan\u00e7ada',
    'plan_comp_f2': 'Gr\u00e1fico Tornado \u2014 drivers de valor',
    'plan_comp_f3': 'Monte Carlo (2.000 simula\u00e7\u00f5es)',
    'plan_comp_f4': 'Avalia\u00e7\u00e3o qualitativa + radar de dimens\u00f5es',
    'plan_comp_f5': 'An\u00e1lise de Estrat\u00e9gia de Sa\u00edda',
    'plan_comp_f6': 'Matriz de Risco M&A',
    'plan_comp_f7': 'Plano de Melhoria de Valor (IA)',
    'plan_comp_f8': 'Carta de Opini\u00e3o de Valor',
    'plan_comp_f9': 'Simula\u00e7\u00e3o de rodada de investimento',
    'plan_comp_f10': 'An\u00e1lise estrat\u00e9gica completa por IA',
    'plan_recommended': 'Recomendado',
    'plan_installment_prefix': 'ou',
    'plan_installment_suffix': 'no cart\u00e3o de cr\u00e9dito*',
    'plan_pdf_report_with': 'Relat\u00f3rio PDF com',
    'plan_cta': 'INICIAR VALUA\u00c7\u00c3O',
    'plan_view_sample': 'Ver amostra de relat\u00f3rio \u2197',
    'plan_guarantee': 'Satisfa\u00e7\u00e3o garantida \u00b7 Pagamento seguro \u00b7 Suporte por e-mail',
    'plan_installment_note': '* Planos em parcelas sujeitos a juros e taxas da operadora do cart\u00e3o.',
    'pay_secure_ssl': 'SSL Seguro',
    'pay_privacy': 'Cumpre Privacidade',
    'pay_stripe': 'Powered by Stripe',
    'pay_one_time': 'Pagamento \u00danico',
    'pay_no_sub': 'Sem Assinatura',

    # Partners
    'partners_label': 'Parceiros',
    'partners_title': 'Transforme indica\u00e7\u00f5es em receita',
    'partners_subtitle': 'Ideal para escrit\u00f3rios cont\u00e1beis, consultorias e firmas de assessoria que desejam oferecer valua\u00e7\u00e3o profissional e pitch deck para investidores como servi\u00e7o adicional \u2014 e ganhar 50% de cada venda.',
    'partners_comm_title': '50% \u2014 Valua\u00e7\u00e3o e Pitch Deck',
    'partners_comm_desc': 'Comiss\u00e3o em ambos os produtos. Cada venda \u2014 valua\u00e7\u00e3o ou pitch deck \u2014 voc\u00ea ganha metade. Sem teto de ganhos.',
    'partners_mgmt_title': 'Gest\u00e3o completa',
    'partners_mgmt_desc': 'Painel exclusivo para acompanhar clientes, status e comiss\u00f5es em tempo real.',
    'partners_portfolio_title': 'Seu portf\u00f3lio cresce',
    'partners_portfolio_desc': 'Ofere\u00e7a valua\u00e7\u00e3o e pitch deck para investidores sem investir em equipe ou tecnologia.',
    'partners_link_title': 'Link de indica\u00e7\u00e3o',
    'partners_link_desc': 'Compartilhe seu link. Cada cadastro \u00e9 rastreado automaticamente.',
    'partners_hiw_title': 'Como funciona',
    'partners_hiw_step1_title': 'Cadastre-se como parceiro',
    'partners_hiw_step1_desc': 'Crie sua conta e ative o Modo Parceiro em segundos. Receba um link de indica\u00e7\u00e3o exclusivo.',
    'partners_hiw_step2_title': 'Indique seus clientes',
    'partners_hiw_step2_desc': 'Compartilhe seu link ou cadastre clientes diretamente no painel. Cada valua\u00e7\u00e3o ou pitch deck \u00e9 rastreado automaticamente.',
    'partners_hiw_step3_title': 'Receba suas comiss\u00f5es',
    'partners_hiw_step3_desc': 'A cada pagamento confirmado \u2014 seja valua\u00e7\u00e3o ou pitch deck \u2014 50% \u00e9 creditado automaticamente na sua conta.',
    'partners_cta_badge': '50% COMISS\u00c3O',
    'partners_cta_title': 'Dividimos 50/50',
    'partners_cta_subtitle': 'Cada venda que voc\u00ea indicar, metade \u00e9 sua.',
    'partners_cta_desc': 'Valua\u00e7\u00e3o profissional (R$ 990+) ou Pitch Deck para investidores (R$ 897). Voc\u00ea indica, o cliente paga e o dinheiro vai para sua conta. Sem teto de ganhos.',
    'partners_cta_button': 'Quero ser parceiro e ganhar 50%',
    'partners_cta_checks': '\u2713 Cadastro em 30 segundos \u00b7 \u2713 Link exclusivo \u00b7 \u2713 Painel com analytics completa',

    # Objections
    'obj_label': 'Direto ao ponto',
    'obj_title': 'O que te impede de come\u00e7ar agora?',
    'obj_q1': 'Minha empresa \u00e9 pequena demais?',
    'obj_a1': 'Nenhuma empresa \u00e9 pequena demais para uma valua\u00e7\u00e3o. O motor se calibra pelo seu setor e maturidade \u2014 de aut\u00f4nomos at\u00e9 empresas com R$ 50M em receita.',
    'obj_q2': 'Preciso de um contador para usar?',
    'obj_a2': 'De jeito nenhum. O formul\u00e1rio \u00e9 guiado. Se voc\u00ea sabe sua receita anual e margem aproximada, pode terminar em menos de 5 minutos.',
    'obj_q3': 'Nunca fiz uma valua\u00e7\u00e3o. \u00c9 para mim?',
    'obj_a3': 'Exatamente para voc\u00ea. O relat\u00f3rio foi projetado para qualquer dono de neg\u00f3cio \u2014 cada indicador \u00e9 explicado em linguagem clara, sem jarg\u00e3o.',
    'obj_q4': 'Investidores v\u00e3o aceitar esse relat\u00f3rio?',
    'obj_a4': 'Sim. Segue a metodologia padr\u00e3o DCF de M&A \u2014 metodologia de c\u00e1lculo completa, benchmark setorial e an\u00e1lise de sensibilidade inclusas.',

    # FAQ
    'faq_label': 'Perguntas frequentes',
    'faq_subtitle': 'Tudo que voc\u00ea precisa saber antes de come\u00e7ar',
    'faq_q1': 'Minha valua\u00e7\u00e3o \u00e9 confidencial?',
    'faq_a1': 'Sim. Seus dados financeiros s\u00e3o criptografados de ponta a ponta e nunca s\u00e3o compartilhados com terceiros.',
    'faq_q2': 'Pode ser usado para captar investimento?',
    'faq_a2': 'Sim. O relat\u00f3rio usa a mesma metodologia DCF das consultorias de M&A, com metodologia de c\u00e1lculo, premissas e benchmark setorial \u2014 pronto para apresentar a investidores e fundos.',
    'faq_q3': 'Quanto tempo demora para chegar o resultado?',
    'faq_a3': 'A valua\u00e7\u00e3o \u00e9 gerada em minutos. Ap\u00f3s o pagamento, o relat\u00f3rio PDF completo \u00e9 enviado ao seu e-mail automaticamente.',
    'faq_q4': 'Posso usar para negociar a venda da empresa?',
    'faq_a4': 'Com certeza. O relat\u00f3rio inclui faixa de valor, cen\u00e1rios pessimista/otimista e benchmark setorial \u2014 documenta\u00e7\u00e3o que fortalece sua posi\u00e7\u00e3o em qualquer negocia\u00e7\u00e3o.',
    'faq_q5': 'O pagamento \u00e9 recorrente?',
    'faq_a5': 'N\u00e3o. \u00c9 um pagamento \u00fanico por an\u00e1lise. Sem assinatura, sem cobran\u00e7as recorrentes.',
    'faq_q6': 'De onde v\u00eam os dados setoriais?',
    'faq_a6': 'Base de dados setorial propriet\u00e1ria com mais de 50 segmentos industriais, calibrada com metodologia Damodaran e dados de mercado atualizados regularmente.',

    # Final CTA
    'cta_title_line1': 'Voc\u00ea criou sua empresa.',
    'cta_title_line2': 'Agora descubra quanto ela realmente vale.',
    'cta_subtitle': 'Valua\u00e7\u00e3o profissional. Com dados oficiais. Em minutos.',
    'cta_button': 'Iniciar valua\u00e7\u00e3o',
    'cta_subtext': 'Sem assinatura \u00b7 Resultados em minutos',

    # Footer
    'footer_desc': 'Valua\u00e7\u00e3o profissional com metodologia DCF e benchmarks setoriais calibrados.',
    'footer_col_product': 'Produto',
    'footer_link_valuation': 'Valua\u00e7\u00e3o DCF',
    'footer_link_pitch': 'Pitch Deck',
    'footer_link_methodology': 'Metodologia',
    'footer_link_features': 'Recursos',
    'footer_col_legal': 'Legal',
    'footer_col_contact': 'Contato',
    'footer_become_partner': 'Seja Parceiro',
    'footer_partner_login': 'Login Parceiro',
    'footer_copyright': '\u00a9 {year} Valuora. Todos os direitos reservados.',

    # Mobile Bar
    'mobile_cta_pitch': 'Criar meu pitch deck',
    'mobile_cta_valuation': 'Iniciar valua\u00e7\u00e3o',

    # Dashboard Page
    'dash_sort_most_recent': 'Mais recente',
    'dash_sort_oldest': 'Mais antigo',
    'dash_sort_highest_value': 'Maior valor',
    'dash_sort_lowest_value': 'Menor valor',
    'dash_sort_a_z': 'A \u2192 Z',
    'dash_sort_z_a': 'Z \u2192 A',
    'dash_tip_ke_title': 'O Ke importa',
    'dash_tip_ke_text': 'O custo do patrim\u00f4nio (Ke) \u00e9 o principal driver da valua\u00e7\u00e3o. Pequenas mudan\u00e7as podem mover o resultado em milh\u00f5es.',
    'dash_tip_dlom_title': 'DLOM reduz o valor',
    'dash_tip_dlom_text': 'Empresas privadas recebem desconto de 10-35% por falta de liquidez. Quanto menor e mais jovem a empresa, maior o desconto.',
    'dash_tip_tv_title': 'Valor Terminal',
    'dash_tip_tv_text': 'Em m\u00e9dia, 60\u201380% do valor vem do Valor Terminal. Se esse percentual \u00e9 alto, a valua\u00e7\u00e3o depende muito de premissas futuras.',
    'dash_tip_multiples_title': 'M\u00faltiplos setoriais',
    'dash_tip_multiples_text': 'Use EV/EBITDA e EV/Revenue do seu setor como refer\u00eancia informativa. Na v4 n\u00e3o comp\u00f5em o valor final.',
    'dash_tip_survival_title': 'Sobreviv\u00eancia',
    'dash_tip_survival_text': 'No modelo v4, a taxa de sobreviv\u00eancia est\u00e1 incorporada diretamente no Valor Terminal \u2014 n\u00e3o \u00e9 um desconto separado.',
    'dash_tip_keyperson_title': 'Risco de Pessoa-Chave',
    'dash_tip_keyperson_text': 'Na v4, o risco de pessoa-chave est\u00e1 incorporado no Ke como um pr\u00eamio de 0\u20134%. Construa um time para reduzir esse custo.',
    'dash_tip_qualitative_title': 'Pontua\u00e7\u00e3o Qualitativa',
    'dash_tip_qualitative_text': 'Fatores como equipe, mercado, produto, tra\u00e7\u00e3o e opera\u00e7\u00f5es ajustam \u00b115% do valor. Complete o question\u00e1rio para maior precis\u00e3o.',
    'dash_good_morning': 'Bom dia',
    'dash_good_afternoon': 'Boa tarde',
    'dash_good_evening': 'Boa noite',
    'dash_completed_this_month': 'conclu\u00eddos este m\u00eas',
    'dash_csv_btn': 'CSV',
    'dash_new_analysis': 'Novo an\u00e1lise',
    'dash_pitch_deck': 'Pitch Deck',
    'dash_filters_title': 'Filtros',
    'dash_search_placeholder': 'Buscar\u2026',
    'dash_all_statuses': 'Todos os status',
    'dash_status_completed': 'Conclu\u00eddo',
    'dash_status_processing': 'Processando',
    'dash_status_draft': 'Rascunho',
    'dash_any_date': 'Qualquer data',
    'dash_last_7_days': '\u00daltimos 7 dias',
    'dash_last_30_days': '\u00daltimos 30 dias',
    'dash_last_90_days': '\u00daltimos 90 dias',
    'dash_all_sectors': 'Todos os setores',
    'dash_any_value': 'Qualquer valor',
    'dash_below_500k': 'Menos de R$ 500K',
    'dash_500k_1m': 'R$ 500K \u2013 R$ 1M',
    'dash_1m_5m': 'R$ 1M \u2013 R$ 5M',
    'dash_above_5m': 'Mais de R$ 5M',
    'dash_favorites_only': 'Somente favoritos',
    'dash_view_grid': 'Grade',
    'dash_view_list': 'Lista',
    'dash_clear_filters': 'Limpar filtros',
    'dash_monthly_goal': 'Meta mensal',
    'dash_goal_reached': 'Meta alcan\u00e7ada!',
    'dash_analysis_created_singular': 'an\u00e1lise criada',
    'dash_analysis_created_plural': 'an\u00e1lises criadas',
    'dash_max_level': 'N\u00edvel m\u00e1ximo',
    'dash_total_portfolio_value': 'Valor total do portf\u00f3lio',
    'dash_active_portfolio': 'Portf\u00f3lio ativo',
    'dash_tip_of_the_day': 'Dica do dia',
    'dash_latest_analysis': '\u00daltima an\u00e1lise',
    'dash_portfolio_evolution': 'Evolu\u00e7\u00e3o do Portf\u00f3lio',
    'dash_analysis_comparator': 'Comparador de An\u00e1lises',
    'dash_recent_activity': 'Atividade Recente',
    'dash_my_payments': 'Meus Pagamentos',
    'dash_hide': 'Ocultar',
    'dash_view_all': 'Ver tudo',
    'dash_table_company': 'Empresa',
    'dash_table_plan': 'Plano',
    'dash_table_amount': 'Valor',
    'dash_table_status': 'Status',
    'dash_table_date': 'Data',
    'dash_payment_paid': 'Pago',
    'dash_payment_pending': 'Pendente',
    'dash_payment_refunded': 'Reembolsado',
    'dash_payment_failed': 'Falhou',
    'dash_welcome': 'Bem-vindo \u00e0 Valuora!',
    'dash_welcome_desc': 'Descubra o valor real da sua empresa com an\u00e1lise profissional baseada em DCF e benchmarks setoriais calibrados.',
    'dash_create_first_analysis': 'Criar minha primeira an\u00e1lise',
    'dash_step_fill_data': 'Preencha os dados',
    'dash_step_fill_desc': 'Receita, margem, crescimento ou upload de DRE',
    'dash_step_engine': 'O motor DCF calcula',
    'dash_step_engine_desc': 'DCF + IA processa em segundos',
    'dash_step_report': 'Receba o relat\u00f3rio',
    'dash_step_report_desc': 'PDF executivo pronto para investidores',
    'dash_unlock_report': 'Desbloquear o relat\u00f3rio completo',
    'dash_view_plans': 'Ver planos',
    'dash_time_to_update': 'Hora de atualizar sua valua\u00e7\u00e3o',
    'dash_analysis_found_singular': 'an\u00e1lise encontrada',
    'dash_analysis_found_plural': 'an\u00e1lises encontradas',
    'dash_compare_valuations': 'Comparar valua\u00e7\u00f5es',
    'dash_error_loading': 'Erro ao carregar an\u00e1lises.',
    'dash_try_again': 'Tentar novamente',
    'dash_create_first_5min': 'Crie sua primeira valua\u00e7\u00e3o em 5 minutos',
    'dash_no_analysis_found': 'Nenhuma an\u00e1lise encontrada',
    'dash_awaiting_result': 'Aguardando resultado',
    'dash_col_company': 'Empresa',
    'dash_col_sector': 'Setor',
    'dash_col_value': 'Valor',
    'dash_col_status': 'Status',
    'dash_col_risk': 'Risco',
    'dash_col_date': 'Data',
    'dash_delete_title': 'Mover para a lixeira',
    'dash_delete_message': '"{name}" ser\u00e1 movido para a lixeira e exclu\u00eddo permanentemente ap\u00f3s 30 dias.',
    'dash_quick_edit_heading': 'Edi\u00e7\u00e3o r\u00e1pida',
    'dash_field_company_name': 'Nome da empresa',
    'dash_field_annual_revenue': 'Receita Anual (R$)',
    'dash_field_net_margin': 'Margem L\u00edquida (%)',
    'dash_field_ebitda': 'EBITDA (R$)',

    # Login Page
    'login_heading': 'Entrar',
    'login_subtitle': 'Fa\u00e7a login na sua conta para continuar.',
    'login_companies_valued': 'empresas avaliadas',
    'login_report_5min': 'Relat\u00f3rio em 5 min',
    'login_sector_benchmarks': 'Benchmarks setoriais',
    'login_hero_heading': 'Acesso exclusivo para an\u00e1lise profissional.',
    'login_hero_desc': 'Fa\u00e7a login e acesse seus relat\u00f3rios de valua\u00e7\u00e3o com dados reais.',
    'login_back_to_home': 'Voltar ao in\u00edcio',
    'login_email_label': 'E-mail',
    'login_password_label': 'Senha',
    'login_forgot_password': 'Esqueceu sua senha?',
    'login_logging_in': 'Entrando...',
    'login_submit': 'Entrar',
    'login_resend_verification': 'N\u00e3o recebeu o e-mail de verifica\u00e7\u00e3o? Reenviar',
    'login_no_account': 'N\u00e3o tem uma conta?',
    'login_create_account': 'Criar conta',

    # Register Page
    'reg_heading': 'Criar Conta',
    'reg_subtitle': 'Preencha seus dados para come\u00e7ar.',
    'reg_companies_valued': '500+ empresas avaliadas',
    'reg_report_5min': 'Relat\u00f3rio em 5 min',
    'reg_sector_benchmarks': 'Benchmarks setoriais',
    'reg_hero_heading': 'Crie sua conta profissional.',
    'reg_hero_desc': 'Cadastre-se e gere relat\u00f3rios de valua\u00e7\u00e3o em minutos com dados reais.',
    'reg_back_to_home': 'Voltar ao in\u00edcio',
    'reg_referred_by': 'Voc\u00ea foi indicado por',
    'reg_fullname_label': 'Nome completo',
    'reg_email_label': 'E-mail',
    'reg_taxid_label': 'CPF / CNPJ *',
    'reg_taxid_hint': 'Necess\u00e1rio para processamento de pagamentos',
    'reg_additional_details': 'Detalhes adicionais (opcional)',
    'reg_phone_label': 'Telefone',
    'reg_company_label': 'Empresa',
    'reg_password_label': 'Senha',
    'reg_min_8_chars': 'M\u00ednimo 8 caracteres',
    'reg_has_uppercase': 'Pelo menos uma letra mai\u00fascula',
    'reg_has_number': 'Pelo menos um n\u00famero',
    'reg_strength_label': 'For\u00e7a:',
    'reg_confirm_password_label': 'Confirmar Senha',
    'reg_passwords_no_match': 'As senhas n\u00e3o coincidem',
    'reg_creating': 'Criando conta...',
    'reg_submit': 'Criar Conta',
    'reg_agree_prefix': 'Ao criar sua conta, voc\u00ea aceita os',
    'reg_terms_of_use': 'Termos de Uso',
    'reg_agree_and': 'e a',
    'reg_privacy_policy': 'Pol\u00edtica de Privacidade',
    'reg_have_account': 'J\u00e1 tem uma conta?',

    # Profile Page
    'profile_heading': 'Meu Perfil',
    'profile_subtitle': 'Gerencie suas informa\u00e7\u00f5es e configura\u00e7\u00f5es de conta.',
    'profile_personal_info': 'Informa\u00e7\u00f5es Pessoais',
    'profile_email_label': 'E-mail',
    'profile_fullname_label': 'Nome completo',
    'profile_phone_label': 'Telefone',
    'profile_company_label': 'Empresa',
    'profile_saving': 'Salvando...',
    'profile_save_changes': 'Salvar altera\u00e7\u00f5es',
    'profile_change_password': 'Alterar Senha',
    'profile_current_pw_label': 'Senha atual',
    'profile_new_pw_label': 'Nova senha',
    'profile_confirm_pw_label': 'Confirmar nova senha',
    'profile_changing': 'Alterando...',
    'profile_change_pw_btn': 'Alterar senha',
    'profile_data_privacy': 'Dados e Privacidade',
    'profile_export_title': 'Exportar meus dados',
    'profile_export_desc': 'Baixe todos os seus dados pessoais e an\u00e1lises em formato JSON.',
    'profile_exporting': 'Exportando...',
    'profile_export_btn': 'Exportar dados',
    'profile_delete_title': 'Excluir minha conta',
    'profile_delete_desc': 'Esta a\u00e7\u00e3o \u00e9 irrevers\u00edvel. Todos os seus dados, an\u00e1lises e pagamentos ser\u00e3o exclu\u00eddos permanentemente.',
    'profile_delete_btn': 'Excluir conta permanentemente',
    'profile_delete_dialog_title': 'Excluir conta permanentemente?',
    'profile_delete_dialog_msg': 'Todos os seus dados, an\u00e1lises e pagamentos ser\u00e3o exclu\u00eddos permanentemente. Esta a\u00e7\u00e3o N\u00c3O pode ser desfeita.',
    'profile_delete_dialog_confirm': 'Sim, excluir minha conta',
}

# Reconstruct using en.js structure
lines = en_content.split('\n')
out_lines = []

for line in lines:
    if line.strip() == '* English (US) translations \u2014 default language':
        out_lines.append(' * Portugu\u00eas (BR) translations')
        continue

    m = re.match(r'^(\s+)(\w+):\s', line)
    if m:
        indent = m.group(1)
        key = m.group(2)
        if key in PT:
            val = PT[key]
            escaped = val.replace("'", "\\'")
            out_lines.append(f"{indent}{key}: '{escaped}',")
        else:
            out_lines.append(line)
    else:
        out_lines.append(line)

result = '\n'.join(out_lines)

with open('frontend/src/lib/i18n/pt.js', 'w') as f:
    f.write(result)

keys_out = re.findall(r'^\s+(\w+):', result, re.MULTILINE)
print(f'Written pt.js with {len(keys_out)} keys')
